/**
 * Generated by `npm run avatars:generate` — do not edit by hand.
 *
 * Maps each person's id to their optimised avatar. The filenames carry a
 * content hash, so they change whenever the picture does and never otherwise.
 * That is what lets `next.config.ts` serve them `immutable` for a year and
 * the service worker treat them as cache-first.
 *
 * Re-run the script after replacing anything in `assets/avatars/`.
 */

export const AVATAR_SOURCES = {
  clara: "/avatars/clara-47dc2994c1.png",
  emily: "/avatars/emily-fd5ab7fbb3.png",
  hannah: "/avatars/hannah-5090be3683.png",
  james: "/avatars/james-542b6a9115.png",
  nathan: "/avatars/nathan-e1781fbd4e.png",
  sarah: "/avatars/sarah-f240eb2e87.png",
  william: "/avatars/william-fab7a38ded.png",
} as const satisfies Record<string, `/avatars/${string}`>;

export type AvatarId = keyof typeof AVATAR_SOURCES;
