/**
 * The playlist the award ceremony plays from.
 *
 * ---------------------------------------------------------------------------
 * WHY A PLAYLIST AND NOT A FILE
 * ---------------------------------------------------------------------------
 * The app already owns one piece of ceremony music — twenty-two seconds of
 * brass, generated by `scripts/generate-fanfare.mjs` and looped. It is good,
 * and after the fourth Sunday in a row it is *very* familiar. A playlist gives
 * every ceremony a different song without anybody choosing one on the day.
 *
 * The songs are **not** in this repository and must never be. Putting real
 * music in `public/` would mean distributing somebody's recording, which is
 * copyright infringement however private the app is. Streaming it through
 * YouTube's own player is the arrangement that is actually licensed: YouTube
 * serves the audio, YouTube pays the rights, and this app holds nothing but an
 * id.
 *
 * ---------------------------------------------------------------------------
 * WHAT KIND OF PLAYLIST WORKS
 * ---------------------------------------------------------------------------
 * A YouTube Music playlist is a YouTube playlist and shares its id, so the id
 * out of a `music.youtube.com` link is the one to paste here. Three kinds do
 * *not* work, and all three fail the same way — an error from the player, and
 * the ceremony quietly falling back to the fanfare:
 *
 *   **Private playlists.** Embedding requires public or unlisted. Unlisted is
 *   enough and is not findable by anybody who does not have the link.
 *   **Auto-generated ones.** "Liked Music" (`LM`), supermixes and radio
 *   (`RD…`) belong to an account rather than to a URL, and cannot be embedded.
 *   **Playlists of videos whose uploaders disabled embedding.** One such video
 *   is skipped; a playlist made entirely of them plays nothing.
 *
 * ---------------------------------------------------------------------------
 * THE PLAYER IS HIDDEN, AND THAT IS A CHOICE WITH A CAVEAT
 * ---------------------------------------------------------------------------
 * The ceremony is a full-screen sequence of slides and a YouTube player in the
 * corner of it would be furniture over the thing the family is watching. So it
 * is positioned off-screen and only ever heard.
 *
 * YouTube's Required Minimum Functionality policy asks for an embedded player
 * at least 200x200 with more than half of it visible before playback starts,
 * so a hidden one is outside those terms. It was a deliberate call for a
 * private family app behind a login rather than an oversight, and it is
 * written down here so that whoever finds it next knows it was decided rather
 * than missed. A visible player belongs on the title slide, beside the Start
 * button, if that ever needs revisiting.
 */

/**
 * The playlist id, or an empty string for "no playlist configured".
 *
 * From a YouTube Music or YouTube URL, it is the `list=` parameter:
 *
 *   https://music.youtube.com/playlist?list=PLxxxxxxxxxxxxxxxx
 *                                           ^^^^^^^^^^^^^^^^^^
 *
 * Empty is a supported state, not a broken one: the ceremony plays its own
 * fanfare exactly as it did before this file existed. That is what makes the
 * whole feature safe to ship un-configured.
 */
/*
 * Annotated `string` rather than left to infer. Without it TypeScript narrows
 * the value to its own literal type, and every `=== ""` check against it — the
 * empty-playlist path, and the test that guards it — becomes a compile error
 * about comparing two types that "have no overlap". The empty state is real
 * and has to stay expressible.
 */
export const CEREMONY_PLAYLIST_ID: string = "PLU3y-28p3eac";

/**
 * How loud a playlist song plays, 0-1.
 *
 * Lower than the fanfare's 0.42, and deliberately. The fanfare was written for
 * this — it is thin, brassy and sits under a voice on purpose. A real record is
 * mastered to be the thing you are listening to, so at the same number it
 * would bury the person reading a child's name out.
 */
export const PLAYLIST_VOLUME = 0.28;

/**
 * How long to wait for YouTube before giving up and playing the fanfare.
 *
 * Generous, because it covers a cold script fetch on a kitchen iPad over a
 * slow connection — and bounded, because the alternative to giving up is a
 * ceremony that starts in silence and stays there. Four seconds is longer than
 * the title slide is on screen, so the fallback is inaudible when it happens.
 */
export const PLAYLIST_TIMEOUT_MS = 4000;

/** `true` when a playlist has actually been configured. */
export function hasCeremonyPlaylist(): boolean {
  return CEREMONY_PLAYLIST_ID.trim().length > 0;
}

/**
 * Whether `id` is a playlist that can be embedded at all.
 *
 * A shape check, not a permissions check — only YouTube can tell us whether a
 * playlist is public. It catches the two mistakes that are easy to make and
 * hard to diagnose: pasting a whole URL instead of the id, and pasting one of
 * the account-bound playlists that can never be embedded no matter what its
 * privacy is set to.
 */
export function isEmbeddablePlaylistId(id: string): boolean {
  const value = id.trim();
  if (value.length === 0) return false;
  // A pasted URL, or anything with punctuation an id does not have.
  if (!/^[A-Za-z0-9_-]+$/.test(value)) return false;
  // `LM` is Liked Music and `RD…` is radio or a mix; both belong to an account
  // rather than to a URL, and neither can be embedded.
  if (value === "LM" || value.startsWith("RD")) return false;
  return true;
}
