/**
 * Generated by `npm run documents:generate` — do not edit by hand.
 *
 * Maps each document's id to its optimised full view and thumbnail. The
 * filenames carry a content hash, so they change whenever the photo does and
 * never otherwise. That is what lets `next.config.ts` serve them
 * `immutable` for a year and the service worker treat them as cache-first.
 *
 * Re-run the script after replacing anything in `assets/documents/`.
 */

export type DocumentImage = {
  src: `/documents/${string}`;
  width: number;
  height: number;
};

export const DOCUMENT_SOURCES = {
  "elementary-lunch-menu": {
    full: { src: "/documents/elementary-lunch-menu-a5bfa1e7d8.jpg", width: 1600, height: 1232 },
    thumb: { src: "/documents/elementary-lunch-menu-e706879332-thumb.jpg", width: 360, height: 277 },
  },
  "first-grade-welcome": {
    full: { src: "/documents/first-grade-welcome-e1361568b4.jpg", width: 1600, height: 1200 },
    thumb: { src: "/documents/first-grade-welcome-a9dd5df20d-thumb.jpg", width: 360, height: 270 },
  },
  "mms-lunch-menu": {
    full: { src: "/documents/mms-lunch-menu-4ee61caa70.jpg", width: 1600, height: 1232 },
    thumb: { src: "/documents/mms-lunch-menu-bf417ae6c9-thumb.jpg", width: 360, height: 277 },
  },
} as const satisfies Record<string, { full: DocumentImage; thumb: DocumentImage }>;

export type DocumentImageId = keyof typeof DOCUMENT_SOURCES;
