/**
 * The Birch family's own recipes — the ones they actually cook — added as the
 * second seed batch (see `SeedBatch` in `config/meals-seed.ts`).
 *
 * Generated on 2026-09-28 from the pages the family listed: every ingredient
 * line was read from the recipe itself (an archived copy where the site blocked
 * reading it), converted into the catalog's units, and the method rewritten in
 * short steps of our own. Eight have no web page — the frozen breads, BLTs,
 * walking tacos, tacos and the smoothie — and are house recipes.
 *
 * Applied to a database once, the first time the app runs with it. After that
 * the recipes belong to the family: edit them from the Meals page, not here.
 *
 * New ingredients' prices are estimates, like the starter catalog's, and say
 * so on the Prices tab until somebody checks them.
 */

import type { SeedBatch, SeedIngredient, SeedRecipe } from "./meals-seed";

const INGREDIENTS: readonly SeedIngredient[] = [
  { key: "cider-vinegar", name: "Apple cider vinegar", unit: "tbsp", packLabel: "32 oz bottle", packUnits: 64, prices: { Walmart: 2.12, "Broulim's": 2.99 }, nutrition: [3,0.1,0.1,0,0] },
  { key: "ground-ginger", name: "Ground ginger", unit: "tsp", packLabel: "1.5 oz jar", packUnits: 23, prices: { Walmart: 2.38, "Broulim's": 3.49 }, nutrition: [6,1.3,0,0.2,0.1] },
  { key: "fresh-ginger", name: "Ginger root", unit: "tbsp", packLabel: "3 oz piece", packUnits: 6, prices: { Walmart: 0.75, "Broulim's": 0.99 }, nutrition: [5,1,0.1,0.1,0] },
  { key: "orange", name: "Oranges", unit: "orange", packLabel: "each", packUnits: 1, prices: { Walmart: 0.68, "Broulim's": 0.99 }, nutrition: [62,15,12,1.2,0.2] },
  { key: "orange-juice", name: "Orange juice", unit: "cup", packLabel: "52 oz carton", packUnits: 6.5, prices: { Walmart: 3.48, "Broulim's": 4.29 }, nutrition: [112,26,21,1.7,0.5] },
  { key: "red-pepper-flakes", name: "Crushed red pepper flakes", unit: "tsp", packLabel: "1.5 oz jar", packUnits: 25, prices: { Walmart: 1.98, "Broulim's": 2.49 }, nutrition: [6,1,0.2,0.2,0.3] },
  { key: "mirin", name: "Rice wine (mirin)", unit: "tbsp", packLabel: "10 oz bottle", packUnits: 20, prices: { Walmart: 3.48, "Broulim's": 4.29 }, nutrition: [35,7,4.5,0,0] },
  { key: "rice-vinegar", name: "Rice vinegar", unit: "tbsp", packLabel: "12 oz bottle", packUnits: 24, prices: { Walmart: 2.48, "Broulim's": 3.29 }, nutrition: [0,0,0,0,0] },
  { key: "sesame-oil", name: "Toasted sesame oil", unit: "tbsp", packLabel: "5 oz bottle", packUnits: 10, prices: { Walmart: 3.98, "Broulim's": 4.99 }, nutrition: [120,0,0,0,14] },
  { key: "yakisoba", name: "Yakisoba noodles, refrigerated", unit: "package", packLabel: "3 × 5.6 oz", packUnits: 3, prices: { Walmart: 4.24, "Broulim's": 4.99 }, nutrition: [280,52,2,8,4] },
  { key: "cabbage", name: "Green cabbage", unit: "cup", packLabel: "1 head (~2 lb)", packUnits: 10, prices: { Walmart: 1.68, "Broulim's": 1.98 }, nutrition: [22,5,3,1.1,0.1] },
  { key: "pork-ribs", name: "Boneless country-style pork ribs", unit: "lb", packLabel: "3 lb pack", packUnits: 3, prices: { Walmart: 10.47, "Broulim's": 11.97 }, nutrition: [907,0,0,80,64], costco: [17.94, "6 lb pack", 6] },
  { key: "coke", name: "Coca-Cola", unit: "can", packLabel: "12 pack (12 oz cans)", packUnits: 12, prices: { Walmart: 8.98, "Broulim's": 9.99 }, nutrition: [140,39,39,0,0], costco: [17.99, "35 pack", 35] },
  { key: "garlic-salt", name: "Garlic salt", unit: "tsp", packLabel: "4.75 oz jar", packUnits: 32, prices: { Walmart: 1.24, "Broulim's": 1.79 }, nutrition: [0,0,0,0,0] },
  { key: "buttermilk", name: "Buttermilk", unit: "cup", packLabel: "1 quart", packUnits: 4, prices: { Walmart: 2.34, "Broulim's": 2.79 }, nutrition: [98,12,12,8,2.2] },
  { key: "tomatillo", name: "Tomatillos", unit: "tomatillo", packLabel: "each", packUnits: 1, prices: { Walmart: 0.25, "Broulim's": 0.33 }, nutrition: [11,2,1.3,0.3,0.3] },
  { key: "tomato-juice", name: "Tomato juice", unit: "cup", packLabel: "46 oz bottle", packUnits: 5.75, prices: { Walmart: 2.48, "Broulim's": 2.99 }, nutrition: [41,9,6,2,0.1] },
  { key: "hot-sauce", name: "Hot sauce", unit: "tsp", packLabel: "10 oz bottle", packUnits: 60, prices: { Walmart: 2.48, "Broulim's": 3.19 }, nutrition: [0,0,0,0,0] },
  { key: "chow-mein-noodles", name: "Chow mein noodles, crispy", unit: "cup", packLabel: "5 oz can", packUnits: 2.75, prices: { Walmart: 2.28, "Broulim's": 2.99 }, nutrition: [276,31,1,4,15] },
  { key: "cashews", name: "Cashews", unit: "cup", packLabel: "8 oz can", packUnits: 1.65, prices: { Walmart: 3.98, "Broulim's": 5.49 }, nutrition: [786,45,8,21,63] },
  { key: "coconut", name: "Shredded coconut, sweetened", unit: "cup", packLabel: "7 oz bag", packUnits: 2.1, prices: { Walmart: 2.48, "Broulim's": 3.29 }, nutrition: [466,44,40,3,33] },
  { key: "black-olives", name: "Black olives", unit: "cup", packLabel: "6 oz can (drained)", packUnits: 1.25, prices: { Walmart: 1.28, "Broulim's": 1.79 }, nutrition: [155,8,0,1.1,14.4] },
  { key: "pepperoncini", name: "Pepperoncini", unit: "cup", packLabel: "16 oz jar", packUnits: 2, prices: { Walmart: 2.48, "Broulim's": 3.29 }, nutrition: [30,6,3,1,0.3] },
  { key: "red-onion", name: "Red onion", unit: "onion", packLabel: "each", packUnits: 1, prices: { Walmart: 0.98, "Broulim's": 1.29 }, nutrition: [44,10,4.7,1.2,0.1] },
  { key: "croutons", name: "Croutons", unit: "cup", packLabel: "5 oz bag", packUnits: 4.7, prices: { Walmart: 1.68, "Broulim's": 2.49 }, nutrition: [140,19,1.5,3,5] },
  { key: "salad-mix", name: "Garden salad mix, bagged", unit: "cup", packLabel: "12 oz bag", packUnits: 4, prices: { Walmart: 1.98, "Broulim's": 2.49 }, nutrition: [12,2.5,1,0.7,0.1] },
  { key: "italian-dressing", name: "Italian dressing", unit: "tbsp", packLabel: "16 oz bottle", packUnits: 32, prices: { Walmart: 1.98, "Broulim's": 2.79 }, nutrition: [35,2,1.5,0,3] },
  { key: "italian-sausage", name: "Italian sausage, ground", unit: "lb", packLabel: "1 lb pack", packUnits: 1, prices: { Walmart: 4.47, "Broulim's": 4.99 }, nutrition: [1450,2,1,64,128] },
  { key: "kale", name: "Kale, chopped", unit: "cup", packLabel: "10 oz bag", packUnits: 13, prices: { Walmart: 2.48, "Broulim's": 2.99 }, nutrition: [7,0.9,0.2,0.6,0.3] },
  { key: "gold-potatoes", name: "Yellow (Yukon gold) potatoes", unit: "lb", packLabel: "5 lb bag", packUnits: 5, prices: { Walmart: 4.47, "Broulim's": 5.49 }, nutrition: [320,72,3,8,0.4] },
  { key: "dry-black-beans", name: "Black beans, dried", unit: "lb", packLabel: "2 lb bag", packUnits: 2, prices: { Walmart: 2.98, "Broulim's": 3.49 }, nutrition: [1540,285,10,97,6] },
  { key: "bay-leaves", name: "Bay leaves", unit: "leaf", packLabel: "0.25 oz jar (~40)", packUnits: 40, prices: { Walmart: 1.98, "Broulim's": 2.49 }, nutrition: [0,0,0,0,0] },
  { key: "white-vinegar", name: "White vinegar", unit: "tbsp", packLabel: "32 oz bottle", packUnits: 64, prices: { Walmart: 1.12, "Broulim's": 1.49 }, nutrition: [0,0,0,0,0] },
  { key: "dried-beef", name: "Dried beef", unit: "oz", packLabel: "4.5 oz jar", packUnits: 4.5, prices: { Walmart: 5.48, "Broulim's": 5.99 }, nutrition: [45,1,0,8,1] },
  { key: "smoked-pork-chops", name: "Smoked pork chops", unit: "chop", packLabel: "4 ct pack", packUnits: 4, prices: { Walmart: 7.48, "Broulim's": 8.49 }, nutrition: [250,2,1,30,14] },
  { key: "linguica", name: "Linguiça sausage", unit: "oz", packLabel: "12 oz pack", packUnits: 12, prices: { Walmart: 5.48, "Broulim's": 5.99 }, nutrition: [90,1,0,4.5,7.5] },
  { key: "coriander", name: "Ground coriander", unit: "tsp", packLabel: "1.5 oz jar", packUnits: 23, prices: { Walmart: 2.48, "Broulim's": 3.29 }, nutrition: [5,1,0,0.2,0.3] },
  { key: "cayenne", name: "Cayenne pepper", unit: "tsp", packLabel: "1.5 oz jar", packUnits: 23, prices: { Walmart: 1.98, "Broulim's": 2.49 }, nutrition: [6,1,0.2,0.2,0.3] },
  { key: "parsley", name: "Italian parsley", unit: "bunch", packLabel: "1 bunch", packUnits: 1, prices: { Walmart: 0.78, "Broulim's": 0.99 }, nutrition: [22,4,0.5,2,0.5] },
  { key: "dried-parsley", name: "Parsley flakes", unit: "tbsp", packLabel: "0.4 oz jar", packUnits: 8, prices: { Walmart: 1.24, "Broulim's": 1.79 }, nutrition: [4,0.7,0.1,0.3,0.1] },
  { key: "bread-crumbs", name: "Bread crumbs", unit: "cup", packLabel: "15 oz canister", packUnits: 3.75, prices: { Walmart: 1.98, "Broulim's": 2.79 }, nutrition: [427,78,7,14,6] },
  { key: "garam-masala", name: "Garam masala", unit: "tsp", packLabel: "1.9 oz jar", packUnits: 27, prices: { Walmart: 3.98, "Broulim's": 4.99 }, nutrition: [6,1,0,0.3,0.3] },
  { key: "turmeric", name: "Ground turmeric", unit: "tsp", packLabel: "1.3 oz jar", packUnits: 12, prices: { Walmart: 2.48, "Broulim's": 3.49 }, nutrition: [9,2,0.1,0.3,0.1] },
  { key: "crushed-tomatoes", name: "Crushed tomatoes", unit: "can", packLabel: "28 oz can", packUnits: 1, prices: { Walmart: 1.78, "Broulim's": 2.29 }, nutrition: [210,42,28,10,1] },
  { key: "plain-yogurt", name: "Plain yogurt", unit: "cup", packLabel: "32 oz tub", packUnits: 4, prices: { Walmart: 2.48, "Broulim's": 3.29 }, nutrition: [150,17,17,13,4] },
  { key: "fenugreek", name: "Dried fenugreek leaves (kasoori methi)", unit: "tsp", packLabel: "1 oz bag", packUnits: 30, prices: { Walmart: 5.99 }, nutrition: [3,0.5,0,0.2,0] },
  { key: "paprika", name: "Paprika", unit: "tsp", packLabel: "2.5 oz jar", packUnits: 31, prices: { Walmart: 1.24, "Broulim's": 1.99 }, nutrition: [6,1.2,0.2,0.3,0.3] },
  { key: "tomato-paste", name: "Tomato paste", unit: "can", packLabel: "6 oz can", packUnits: 1, prices: { Walmart: 0.68, "Broulim's": 0.99 }, nutrition: [150,33,21,7,1] },
  { key: "worcestershire", name: "Worcestershire sauce", unit: "tbsp", packLabel: "10 oz bottle", packUnits: 20, prices: { Walmart: 1.98, "Broulim's": 2.99 }, nutrition: [13,3,2,0,0] },
  { key: "basil", name: "Fresh basil", unit: "cup", packLabel: "0.75 oz clamshell", packUnits: 0.75, prices: { Walmart: 1.98, "Broulim's": 2.49 }, nutrition: [5,0.5,0,0.6,0.1] },
  { key: "poblano", name: "Poblano peppers", unit: "pepper", packLabel: "each", packUnits: 1, prices: { Walmart: 0.48, "Broulim's": 0.69 }, nutrition: [20,4,2,1,0.2] },
  { key: "onion-powder", name: "Onion powder", unit: "tsp", packLabel: "2.6 oz jar", packUnits: 31, prices: { Walmart: 1.24, "Broulim's": 1.99 }, nutrition: [8,1.9,0.2,0.2,0] },
  { key: "oregano", name: "Dried oregano", unit: "tsp", packLabel: "0.87 oz jar", packUnits: 25, prices: { Walmart: 1.24, "Broulim's": 1.79 }, nutrition: [3,0.7,0,0.1,0.1] },
  { key: "canned-corn", name: "Whole kernel corn, canned", unit: "can", packLabel: "15.25 oz can", packUnits: 1, prices: { Walmart: 0.78, "Broulim's": 0.99 }, nutrition: [210,45,11,7,2] },
  { key: "fresh-green-beans", name: "Green beans, fresh", unit: "lb", packLabel: "1 lb bag", packUnits: 1, prices: { Walmart: 2.48, "Broulim's": 2.99 }, nutrition: [140,32,15,8,1] },
  { key: "lemon-pepper", name: "Lemon pepper seasoning", unit: "tsp", packLabel: "2.6 oz jar", packUnits: 26, prices: { Walmart: 1.24, "Broulim's": 1.99 }, nutrition: [1,0.2,0,0,0] },
  { key: "balsamic", name: "Balsamic vinegar", unit: "tbsp", packLabel: "16.9 oz bottle", packUnits: 34, prices: { Walmart: 2.97, "Broulim's": 3.99 }, nutrition: [14,2.7,2.4,0.1,0] },
  { key: "lemon-juice", name: "Lemon juice, bottled", unit: "tbsp", packLabel: "15 oz bottle", packUnits: 30, prices: { Walmart: 1.47, "Broulim's": 1.99 }, nutrition: [3,1,0.4,0,0] },
  { key: "rosemary", name: "Dried rosemary", unit: "tsp", packLabel: "0.7 oz jar", packUnits: 16, prices: { Walmart: 1.98, "Broulim's": 2.49 }, nutrition: [4,0.8,0,0.1,0.2] },
  { key: "dijon", name: "Dijon mustard", unit: "tbsp", packLabel: "12 oz jar", packUnits: 24, prices: { Walmart: 1.98, "Broulim's": 2.79 }, nutrition: [15,1,0,1,1] },
  { key: "condensed-milk", name: "Sweetened condensed milk", unit: "can", packLabel: "14 oz can", packUnits: 1, prices: { Walmart: 1.78, "Broulim's": 2.49 }, nutrition: [1300,220,220,32,35] },
  { key: "sprinkles", name: "Chocolate sprinkles", unit: "tbsp", packLabel: "3 oz jar", packUnits: 7, prices: { Walmart: 2.48, "Broulim's": 3.29 }, nutrition: [60,10,8,0,2] },
  { key: "pudding-mix", name: "Instant vanilla pudding mix", unit: "box", packLabel: "3.4 oz box", packUnits: 1, prices: { Walmart: 1.24, "Broulim's": 1.69 }, nutrition: [360,90,72,0,0] },
  { key: "shortening", name: "Vegetable shortening", unit: "tbsp", packLabel: "48 oz can", packUnits: 106, prices: { Walmart: 5.98, "Broulim's": 6.99 }, nutrition: [110,0,0,0,12.5] },
  { key: "maple-syrup", name: "Pure maple syrup", unit: "cup", packLabel: "12.5 oz bottle", packUnits: 1.56, prices: { Walmart: 7.98, "Broulim's": 9.49 }, nutrition: [832,214,190,0,0], costco: [14.99, "1 L bottle", 4.2] },
  { key: "frozen-spinach", name: "Chopped spinach, frozen", unit: "oz", packLabel: "12 oz bag", packUnits: 12, prices: { Walmart: 1.12, "Broulim's": 1.49 }, nutrition: [8,1.2,0.2,1,0.2] },
  { key: "artichokes", name: "Artichoke hearts, canned", unit: "can", packLabel: "14 oz can", packUnits: 1, prices: { Walmart: 2.28, "Broulim's": 2.99 }, nutrition: [100,20,2,6,0.5] },
  { key: "graham-crackers", name: "Graham crackers", unit: "sheet", packLabel: "14.4 oz box (~27 sheets)", packUnits: 27, prices: { Walmart: 3.24, "Broulim's": 3.99 }, nutrition: [65,11,4,1,1.5] },
  { key: "corn-tortillas", name: "Corn tortillas, 6\"", unit: "tortilla", packLabel: "30 ct pack", packUnits: 30, prices: { Walmart: 2.48, "Broulim's": 2.99 }, nutrition: [52,11,0.2,1.4,0.7] },
  { key: "guacamole", name: "Guacamole", unit: "cup", packLabel: "15 oz tub", packUnits: 1.75, prices: { Walmart: 5.48, "Broulim's": 5.99 }, nutrition: [368,20,1.5,4.6,33] },
  { key: "pie-filling", name: "Fruit pie filling", unit: "can", packLabel: "21 oz can", packUnits: 1, prices: { Walmart: 2.48, "Broulim's": 3.29 }, nutrition: [630,154,120,1,0.3] },
  { key: "thyme", name: "Dried thyme", unit: "tsp", packLabel: "0.75 oz jar", packUnits: 21, prices: { Walmart: 1.48, "Broulim's": 1.99 }, nutrition: [3,0.6,0,0.1,0.1] },
  { key: "grape-tomatoes", name: "Grape tomatoes", unit: "cup", packLabel: "10 oz pint", packUnits: 2, prices: { Walmart: 2.48, "Broulim's": 2.99 }, nutrition: [27,6,4,1.3,0.3] },
  { key: "doritos", name: "Doritos, Nacho Cheese", unit: "oz", packLabel: "9.25 oz bag", packUnits: 9.25, prices: { Walmart: 4.98, "Broulim's": 5.49 }, nutrition: [140,18,1,2,7] },
  { key: "chip-snack-bags", name: "Fritos / Doritos snack bags", unit: "bag", packLabel: "20 ct box", packUnits: 20, prices: { Walmart: 9.98, "Broulim's": 11.99 }, nutrition: [150,15,0,2,10], costco: [16.99, "40 ct box", 40] },
  { key: "catalina", name: "Catalina dressing", unit: "tbsp", packLabel: "16 oz bottle", packUnits: 32, prices: { Walmart: 1.98, "Broulim's": 2.79 }, nutrition: [60,4,4,0,5] },
  { key: "croissants", name: "Butter croissants", unit: "croissant", packLabel: "12 ct box", packUnits: 12, prices: { Walmart: 5.48 }, nutrition: [230,26,6,5,12], costco: [7.49, "12 ct box", 12] },
  { key: "gv-garlic-breadsticks", name: "Great Value garlic breadsticks, frozen", unit: "breadstick", packLabel: "10.5 oz bag (8 ct)", packUnits: 8, prices: { Walmart: 2.97 }, nutrition: [140,18,1,4,6] },
  { key: "gv-garlic-knots", name: "Great Value garlic knots, frozen", unit: "knot", packLabel: "13.2 oz bag (12 ct)", packUnits: 12, prices: { Walmart: 3.47 }, nutrition: [90,12,1,2,3.5] },
  { key: "rhodes-rolls", name: "Rhodes white dinner rolls, frozen", unit: "roll", packLabel: "3 lb bag (36 ct)", packUnits: 36, prices: { Walmart: 5.98, "Broulim's": 6.99 }, nutrition: [80,14,1,3,1.5] },
  { key: "rhodes-cinnamon-rolls", name: "Rhodes cinnamon rolls, frozen (with frosting)", unit: "roll", packLabel: "12 ct bag", packUnits: 12, prices: { Walmart: 6.48, "Broulim's": 7.49 }, nutrition: [240,40,18,4,7] },
];

const RECIPES: readonly SeedRecipe[] = [
  {
    key: "fam-baked-teriyaki-chicken",
    name: "Baked Teriyaki Chicken",
    mealTimes: ["dinner"],
    type: "Ethnic",
    feeds: 6,
    activeMinutes: 30,
    totalMinutes: 90,
    tags: ["oven"],
    url: "https://www.allrecipes.com/recipe/9023/baked-teriyaki-chicken/",
    lines: [["cornstarch", 1], ["sugar", 0.5], ["soy-sauce", 8], ["cider-vinegar", 4], ["garlic", 1, "minced"], ["ground-ginger", 0.5], ["pepper", 0.25], ["chicken-thighs", 3, "12 skinless thighs"]],
    steps: ["You'll also need: 1 tablespoon cold water (for the cornstarch).","Stir the cornstarch, cold water, sugar, soy sauce, vinegar, garlic, ginger and pepper together in a small saucepan and simmer on low, stirring often, until the sauce bubbles and thickens.","Heat the oven to 425°F (220°C) and grease a 9x13-inch baking dish.","Lay the chicken thighs in the dish and brush both sides with the sauce.","Bake 30 minutes, flip the pieces, and bake about 30 minutes more until cooked through with clear juices, basting with sauce every 10 minutes."],
  },
  {
    key: "fam-best-chocolate-chip-cookies",
    name: "The Best Chocolate Chip Cookies",
    mealTimes: ["dessert"],
    type: "Dessert",
    feeds: 18,
    activeMinutes: 10,
    totalMinutes: 30,
    tags: ["treat","kid favorite","oven"],
    url: "https://joyfoodsunshine.com/the-most-amazing-chocolate-chip-cookies/",
    lines: [["butter", 16, "softened"], ["sugar", 1], ["brown-sugar", 1, "packed"], ["vanilla", 2], ["eggs", 2], ["flour", 3], ["baking-soda", 1], ["baking-powder", 0.5], ["salt", 1], ["chocolate-chips", 2]],
    steps: ["Heat the oven to 375°F and line baking sheets with parchment.","Whisk the flour, baking soda, baking powder and salt together in a bowl.","In a separate bowl, beat the butter with both sugars, then beat in the eggs and vanilla until light.","Mix in the dry ingredients, then stir in the chocolate chips.","Scoop 2–3 tablespoon balls of dough onto the sheets, spaced apart.","Bake 8–10 minutes, pulling them when the edges are only just starting to brown; rest 2 minutes on the pan before moving to a rack."],
  },
  {
    key: "fam-orange-chicken",
    name: "Panda Express Copycat Orange Chicken",
    mealTimes: ["dinner"],
    type: "Ethnic",
    feeds: 6,
    activeMinutes: 15,
    totalMinutes: 45,
    tags: ["stove top","kid favorite"],
    url: "https://www.food.com/recipe/panda-express-orange-chicken-103215",
    lines: [["chicken-breast", 2, "bite-sized pieces"], ["eggs", 1], ["salt", 1.5], ["vegetable-oil", 6, "for frying — about ¼ of the 1½ cups used is absorbed"], ["cornstarch", 8, "for coating"], ["flour", 0.25], ["soy-sauce", 3, "sauce"], ["orange-juice", 0.75, "sauce"], ["brown-sugar", 0.5, "sauce"], ["orange", 1, "zest, for the sauce"], ["vegetable-oil", 1, "sauce"], ["fresh-ginger", 2, "minced"], ["garlic", 2, "minced"], ["red-pepper-flakes", 1], ["green-onions", 0.5, "chopped"], ["mirin", 2], ["cornstarch", 2, "sauce"], ["sesame-oil", 0.33, "optional"], ["rice", 2, "to serve (not in the original)"]],
    steps: ["You'll also need: white pepper to taste; ½ cup water (for the sauce).","Beat the egg with the salt, white pepper and a tablespoon of oil; in another bowl mix 1/2 cup cornstarch with the flour.","Heat frying oil in a wok or deep fryer to 375°F.","Dip the chicken pieces in the egg mixture, then the flour mixture, and fry in small batches 3–4 minutes until golden; drain on paper towels.","For the sauce, stir together the soy sauce, orange juice, brown sugar and orange zest.","In a clean hot wok, briefly stir-fry the ginger, garlic, chili flakes and green onion in 1 tablespoon oil until fragrant, then add the rice wine and the soy-orange mixture.","Toss in the fried chicken, then stir in the water-cornstarch slurry until the sauce thickens; finish with sesame oil if you like and serve over jasmine rice."],
  },
  {
    key: "fam-chow-mein",
    name: "Panda Express Copycat Chow Mein",
    mealTimes: ["dinner","side"],
    type: "Ethnic",
    feeds: 8,
    activeMinutes: 20,
    totalMinutes: 25,
    tags: ["stove top"],
    url: "https://www.favfamilyrecipes.com/our-version-of-panda-express-chow-mein/",
    lines: [["soy-sauce", 4], ["brown-sugar", 0.0625], ["garlic", 2, "minced"], ["fresh-ginger", 0.33, "grated"], ["vegetable-oil", 2], ["yakisoba", 3, "refrigerated, seasoning packets discarded"], ["celery", 2, "sliced diagonally"], ["onion", 1, "thinly sliced"], ["cabbage", 2, "chopped"]],
    steps: ["You'll also need: black pepper to taste.","Mix the soy sauce, brown sugar, garlic, ginger and pepper in a small bowl.","Unpack the yakisoba noodles, throw away the seasoning packets, then rinse and drain the noodles.","Heat the oil in a wok or large skillet and sauté the celery and onion 1–2 minutes until the onion softens; add the cabbage and cook another minute.","Add the noodles and sauce and stir-fry over medium-high heat 2–3 minutes until hot throughout."],
  },
  {
    key: "fam-cafe-rio-sweet-pork",
    name: "Cafe Rio Sweet Pork",
    mealTimes: ["dinner"],
    type: "Mexican",
    feeds: 10,
    activeMinutes: 15,
    totalMinutes: 495,
    tags: ["crock pot","make ahead","freezer"],
    url: "https://www.favfamilyrecipes.com/cafe-rio-sweet-pork/",
    lines: [["pork-ribs", 2, "boneless pork ribs"], ["coke", 3, "not diet"], ["brown-sugar", 0.25, "for the marinade"], ["garlic-salt", 0.125], ["green-chiles", 1], ["enchilada-sauce", 1, "red, 10 oz"], ["brown-sugar", 1, "for the sauce"]],
    steps: ["You'll also need: ¼ cup water.","Put the pork in a zip-top bag with about 1.5 cans of Coke and 1/4 cup brown sugar and marinate a few hours or overnight.","Discard the marinade and slow-cook the pork with half a can of Coke, the water and the garlic salt (high 3–4 hours or low 8 hours) until it shreds easily.","Take the pork out, pour off the liquid, and shred the meat.","Blend the remaining half can of Coke with the green chilies, enchilada sauce and 1 cup brown sugar, thinning with more Coke if too thick.","Return the shredded pork and sauce to the slow cooker and cook on low 2 more hours."],
  },
  {
    key: "fam-cafe-rio-cilantro-ranch",
    name: "Cafe Rio Cilantro Ranch",
    mealTimes: ["side"],
    type: "Sauce",
    feeds: 10,
    activeMinutes: 10,
    totalMinutes: 10,
    tags: ["no bake"],
    url: "https://www.favfamilyrecipes.com/cafe-rio-cilantro-ranch-dressing/",
    lines: [["ranch-mix", 1, "traditional, not buttermilk"], ["mayo", 16], ["buttermilk", 1], ["tomatillo", 2, "husked, diced"], ["cilantro", 0.5], ["garlic", 1], ["lime", 1, "juiced"], ["jalapeno", 1, "seed it for milder"]],
    steps: ["Put every ingredient into a blender.","Blend until completely smooth.","Use as a salad dressing or a dip for chips and vegetables."],
  },
  {
    key: "fam-cafe-rio-cilantro-lime-rice",
    name: "Cafe Rio Cilantro Lime Rice",
    mealTimes: ["dinner","side"],
    type: "Side",
    feeds: 4,
    activeMinutes: 5,
    totalMinutes: 25,
    tags: ["stove top"],
    url: "https://www.favfamilyrecipes.com/cafe-rio-cilantro-lime-rice-and-black/",
    lines: [["rice", 1, "long-grain white"], ["butter", 0.33], ["garlic", 2, "minced"], ["lime", 0.67, "juiced (1 tsp + 1 tbsp)"], ["chicken-broth", 1.875, "15 oz"], ["sugar", 0.042], ["cilantro", 0.19, "chopped"]],
    steps: ["You'll also need: 1 cup water.","Combine the rice, butter, garlic, 1 teaspoon lime juice, chicken broth and water in a saucepan and bring to a boil.","Cover, turn to low, and cook 15–20 minutes until the rice is tender.","Take off the heat; stir the remaining lime juice, sugar and cilantro together.","Pour the lime mixture over the hot rice and fold it in while fluffing."],
  },
  {
    key: "fam-cafe-rio-black-beans",
    name: "Cafe Rio Black Beans",
    mealTimes: ["dinner","side"],
    type: "Side",
    feeds: 4,
    activeMinutes: 5,
    totalMinutes: 15,
    tags: ["stove top"],
    url: "https://www.favfamilyrecipes.com/black-beans/",
    lines: [["olive-oil", 2], ["garlic", 2, "minced"], ["cumin", 1], ["black-beans", 1, "rinsed and drained"], ["tomato-juice", 1.33], ["salt", 0.5], ["cilantro", 0.125, "chopped"]],
    steps: ["Warm the oil in a large pan over medium heat and cook the garlic and cumin a couple of minutes until fragrant.","Add the beans, tomato juice and salt and simmer, stirring often, until hot and slightly reduced.","Stir in the cilantro right before serving."],
  },
  {
    key: "fam-cafe-rio-pico-de-gallo",
    name: "Cafe Rio Pico de Gallo",
    mealTimes: ["dinner","side"],
    type: "Sauce",
    feeds: 8,
    activeMinutes: 10,
    totalMinutes: 10,
    tags: ["no bake"],
    url: "https://www.favfamilyrecipes.com/salsa-fresca-pico-de-gallo/",
    lines: [["tomato", 5, "finely diced"], ["salt", 0.5], ["onion", 1, "finely diced"], ["garlic", 3, "minced"], ["cilantro", 1, "finely chopped"], ["jalapeno", 1, "chopped (about 2 tbsp)"], ["lime", 0.5, "juiced"], ["hot-sauce", 0.625, "green Tabasco, 5 shakes"]],
    steps: ["Toss the diced tomatoes with the salt in a medium bowl until evenly seasoned.","Add the onion, garlic, cilantro, jalapeño, lime juice and Tabasco and mix well.","Serve at room temperature; if you chill it to let the flavors meld, let it warm back up before serving."],
  },
  {
    key: "fam-chicken-pot-pie",
    name: "Chicken Pot Pie",
    mealTimes: ["dinner"],
    type: "Entree",
    feeds: 6,
    activeMinutes: 25,
    totalMinutes: 65,
    tags: ["oven"],
    url: "https://www.pillsbury.com/recipes/classic-chicken-pot-pie/1401d418-ac0b-4b50-ad09-c6f1243fb992",
    lines: [["pie-crust", 2, "softened"], ["butter", 5.33], ["onion", 0.33, "chopped"], ["flour", 0.33], ["salt", 0.5], ["pepper", 0.25], ["chicken-broth", 1.75], ["milk", 0.5], ["rotisserie-chicken", 0.85, "2½ cups shredded cooked chicken"], ["mixed-veg", 2, "thawed"]],
    steps: ["Let the pie crusts soften and heat the oven to 425°F. Fit one crust into a 9-inch glass pie plate.","Melt the butter in a saucepan and cook the onion until soft, then stir in the flour, salt and pepper.","Slowly whisk in the broth and milk and cook, stirring, until the sauce is smooth and bubbling and has thickened.","Stir in the chicken and vegetables, take off the heat and spoon into the lined pie plate.","Lay the second crust on top, seal and flute the edges, and cut a few slits for steam.","Bake about 15 minutes, shield the edge with foil, then bake 15-25 minutes more until golden and the filling reaches 165°F. Rest 5 minutes before serving."],
  },
  {
    key: "fam-hawaiian-haystacks",
    name: "Hawaiian Haystacks",
    mealTimes: ["dinner"],
    type: "Entree",
    feeds: 6,
    activeMinutes: 10,
    totalMinutes: 33,
    tags: ["stove top","kid favorite"],
    url: "https://www.melskitchencafe.com/hawaiian-haystacks-chicken-sauce-reinvented/",
    lines: [["chicken-breast", 1.25, "bite-size chunks"], ["butter", 3], ["onion", 0.5, "finely chopped"], ["garlic", 3, "minced"], ["salt", 1], ["pepper", 0.5], ["flour", 0.25], ["milk", 2], ["chicken-broth", 1], ["rice", 2, "cooked, to serve"], ["chow-mein-noodles", 2, "topping"], ["cheddar", 1.5, "topping"], ["tomato", 2, "diced, topping"], ["green-onions", 0.6, "sliced, topping"], ["celery", 2, "chopped, topping"], ["bell-pepper", 1, "chopped, topping"], ["black-olives", 0.4, "sliced, topping"], ["pineapple", 1, "tidbits, topping"], ["mandarins", 1, "topping"], ["cashews", 0.5, "topping"], ["coconut", 0.5, "topping"]],
    steps: ["Melt the butter in a large skillet and cook the onion and garlic until soft. If using raw chicken, add it here and cook until no longer pink.","Blend or whisk the milk, flour, broth, salt and pepper together until completely smooth.","Pour the milk mixture into the skillet and stir over medium heat until it bubbles and thickens into a gravy.","Stir in cooked cubed chicken (if not already in the pan) and heat through; adjust seasoning.","Cook the rice while the gravy simmers.","Serve the chicken gravy over rice and let everyone pile on their own toppings."],
  },
  {
    key: "fam-alfredo",
    name: "Alfredo Sauce",
    mealTimes: ["dinner"],
    type: "Pasta",
    feeds: 10,
    activeMinutes: 5,
    totalMinutes: 15,
    tags: ["stove top"],
    url: "https://therecipecritic.com/the-best-homemade-alfredo-sauce-ever/",
    lines: [["butter", 8], ["heavy-cream", 2], ["cream-cheese", 4], ["garlic", 0.5, "minced"], ["garlic-powder", 1], ["italian-seasoning", 1], ["salt", 0.25], ["pepper", 0.25], ["parmesan", 16, "1 cup grated"], ["fettuccine", 1.5, "to serve (not in the original sauce recipe)"]],
    steps: ["Put the butter, cream and cream cheese in a medium saucepan over medium heat and whisk until everything has melted together.","Whisk in the garlic, garlic powder, Italian seasoning, salt and pepper until smooth.","Add the parmesan a little at a time, whisking so it melts in.","Bring to a gentle simmer and keep whisking 3-5 minutes until thickened.","Toss with hot pasta and serve right away."],
  },
  {
    key: "fam-olive-garden-salad",
    name: "Olive Garden Salad",
    mealTimes: ["dinner","side"],
    type: "Salad",
    feeds: 4,
    activeMinutes: 15,
    totalMinutes: 15,
    tags: ["no bake"],
    url: "https://therecipecritic.com/copycat-olive-garden-salad/",
    lines: [["salad-mix", 8, "24 oz of garden salad mix"], ["tomato", 3, "sliced"], ["pepperoncini", 1], ["red-onion", 1, "small, sliced"], ["black-olives", 1, "large"], ["croutons", 1], ["parmesan", 8, "shredded"], ["italian-dressing", 8, "Olive Garden–style dressing (the site's is a separate recipe)"]],
    steps: ["Slice the tomatoes and red onion.","Add the salad mix to a large bowl with the tomatoes, onion, pepperoncini and olives.","Top with the croutons and parmesan.","Toss with Italian-style dressing just before serving."],
  },
  {
    key: "fam-zuppa-toscana",
    name: "Olive Garden Zuppa Toscana",
    mealTimes: ["dinner"],
    type: "Soup",
    feeds: 4,
    activeMinutes: 10,
    totalMinutes: 40,
    tags: ["stove top"],
    url: "https://www.lecremedelacrumb.com/easy-olive-garden-zuppa-toscana-soup/",
    lines: [["italian-sausage", 1, "spicy, or mild for kids"], ["butter", 4], ["onion", 0.5, "diced"], ["garlic", 3, "1 tbsp minced"], ["chicken-broth", 6], ["gold-potatoes", 2, "4–5 potatoes, 1-inch pieces"], ["salt", 3, "or to taste"], ["pepper", 1], ["heavy-cream", 2], ["kale", 4, "chopped"], ["bacon", 4, "chopped, to top"], ["parmesan", 4, "grated, to top"]],
    steps: ["You'll also need: 2 cups water.","Brown the sausage in a large pot for 5-6 minutes, then lift it out with a slotted spoon and set aside.","Melt the butter in the same pot and cook the onion until translucent; add the garlic for about a minute.","Add the broth, water, potatoes, salt and pepper, bring to a boil and cook until the potatoes are tender.","Stir in the kale and cream, then return the sausage to the pot and heat through.","Taste and adjust seasoning; serve topped with parmesan and/or bacon if you like."],
  },
  {
    key: "fam-brazilian-black-beans",
    name: "Brazilian Style Black Beans",
    mealTimes: ["dinner","side"],
    type: "Ethnic",
    feeds: 10,
    activeMinutes: 60,
    totalMinutes: 105,
    tags: ["instant pot"],
    url: "https://braziliankitchenabroad.com/everyday-black-beans/",
    lines: [["dry-black-beans", 1], ["smoked-sausage", 1, "cut into chunks"], ["bay-leaves", 1], ["cumin", 0.5], ["salt", 1], ["white-vinegar", 0.17, "½ tsp"], ["bacon", 4, "cut into lardons"], ["olive-oil", 2], ["onion", 1, "diced"], ["garlic", 6, "minced, or 2 tbsp Brazilian sofrito"]],
    steps: ["You'll also need: black pepper to taste.","Sort and rinse the beans, then soak them in cold water for 30 minutes, drain, and repeat with fresh water.","Put the soaked beans and sausage in an Instant Pot, cover with water, and pressure cook on manual for 30 minutes; quick-release.","Meanwhile, fry the bacon in the olive oil until browned, then cook the onion until see-through and add the sofrito or garlic until fragrant.","Switch the Instant Pot to sauté, add the bay leaf, cumin, salt, pepper and vinegar, and simmer about 15 minutes.","Stir in the bacon and onion mixture and keep simmering until the beans are as thick as you like."],
  },
  {
    key: "fam-feijoada",
    name: "Feijoada",
    mealTimes: ["dinner"],
    type: "Ethnic",
    feeds: 6,
    activeMinutes: 30,
    totalMinutes: 795,
    tags: ["stove top","holiday"],
    url: "https://www.allrecipes.com/recipe/232437/chef-johns-brazilian-feijoada/",
    lines: [["dry-black-beans", 1, "soaked overnight"], ["dried-beef", 3, "chopped"], ["bay-leaves", 1], ["smoked-pork-chops", 2, "in large chunks, bones reserved"], ["bacon", 4, "4 oz, chopped"], ["linguica", 12, "in large chunks"], ["italian-sausage", 0.5, "2 links"], ["onion", 1, "chopped"], ["garlic", 6, "minced"], ["cumin", 1], ["coriander", 0.5], ["cayenne", 0.0625, "a pinch"], ["parsley", 0.07, "1 tbsp chopped"], ["olive-oil", 1, "topping"], ["bread-crumbs", 0.5, "topping"], ["parsley", 0.13, "2 tbsp chopped, topping"], ["orange", 0.5, "2 tsp zest, topping"], ["rice", 2, "to serve (not in the original)"]],
    steps: ["You'll also need: 2 quarts water, plus more as needed; salt and black pepper to taste.","Soak the beans in plenty of water overnight, then drain.","Simmer the beans in the 2 quarts of water with the dried beef, bay leaf and reserved pork chop bones until they start to soften.","Meanwhile brown the bacon, then brown the pork chop chunks, linguica and Italian sausage in the fat; cook the onion and garlic in the same pan.","Add the browned meats, onion mixture, cumin, coriander and cayenne to the beans and simmer gently for several hours, adding water as needed, until the beans are very tender and the stew is thick. Season with salt, pepper and parsley.","For the topping, toast the bread crumbs in the olive oil until golden, then mix in the parsley and orange zest.","Serve the stew in bowls with the crumb topping sprinkled over."],
  },
  {
    key: "fam-butter-chicken",
    name: "Indian Butter Chicken",
    mealTimes: ["dinner"],
    type: "Ethnic",
    feeds: 5,
    activeMinutes: 15,
    totalMinutes: 45,
    tags: ["stove top"],
    url: "https://cafedelites.com/butter-chicken/",
    lines: [["chicken-thighs", 1.75, "28 oz, bite-sized"], ["plain-yogurt", 0.5, "marinade"], ["garlic", 4.5, "1½ tbsp minced, marinade"], ["fresh-ginger", 1, "marinade"], ["garam-masala", 2, "marinade"], ["turmeric", 1], ["cumin", 1, "marinade"], ["chili-powder", 0.33, "1 tsp, Kashmiri if you have it"], ["salt", 1, "marinade"], ["olive-oil", 2], ["butter", 2, "or ghee"], ["onion", 1, "sliced"], ["garlic", 4.5, "1½ tbsp minced, sauce"], ["fresh-ginger", 1, "sauce"], ["cumin", 1.5, "sauce"], ["garam-masala", 1.5, "sauce"], ["coriander", 1], ["crushed-tomatoes", 0.5, "14 oz"], ["chili-powder", 0.33, "1 tsp, sauce"], ["salt", 1.25, "sauce"], ["heavy-cream", 1], ["sugar", 0.0625], ["fenugreek", 0.5], ["rice", 2, "to serve (not in the original)"]],
    steps: ["Mix the chicken with all the marinade ingredients and marinate for at least 30 minutes, or overnight in the fridge.","Sear the chicken in batches in hot oil for about 3 minutes a side, then set aside.","In the same pan, melt the ghee and cook the onion, garlic, ginger and sauce spices until fragrant.","Add the crushed tomatoes, chili powder and salt and simmer 10-15 minutes until thick and darker.","Blend the sauce until smooth (add a splash of water if needed) and return it to the pan.","Stir in the cream, sugar and fenugreek, then add the chicken and its juices and simmer 8-10 minutes until cooked through.","Garnish with cilantro and serve with rice or naan."],
  },
  {
    key: "fam-roasted-potatoes",
    name: "Roasted Potatoes",
    mealTimes: ["side"],
    type: "Side",
    feeds: 6,
    activeMinutes: 10,
    totalMinutes: 45,
    tags: ["oven"],
    url: "https://www.spendwithpennies.com/simple-herb-oven-roasted-potatoes/",
    lines: [["gold-potatoes", 2, "red or yellow, in chunks"], ["olive-oil", 2], ["garlic-powder", 1], ["italian-seasoning", 2, "dried herbs, or 3 tbsp fresh"], ["paprika", 0.5]],
    steps: ["You'll also need: kosher salt and black pepper to taste.","Heat the oven to 425°F.","Scrub the potatoes and cut them into roughly 1-inch cubes. If you like, soak them in cold water for up to an hour to draw out starch, then drain and dry them well.","Toss the potatoes with the oil, garlic powder, herbs, paprika, salt and pepper.","Spread in a single layer on a baking sheet and roast 30-35 minutes until browned and tender."],
  },
  {
    key: "fam-spaghetti-sauce",
    name: "Spaghetti Sauce",
    mealTimes: ["dinner"],
    type: "Pasta",
    feeds: 5,
    activeMinutes: 10,
    totalMinutes: 40,
    tags: ["stove top","freezer"],
    url: "https://tastesbetterfromscratch.com/homemade-spaghetti-sauce/",
    lines: [["ground-beef", 1, "or half Italian sausage"], ["onion", 1, "chopped"], ["tomato-sauce", 1, "15 oz"], ["tomato-paste", 1, "6 oz"], ["italian-seasoning", 0.5], ["dried-parsley", 1], ["garlic-powder", 1], ["worcestershire", 1], ["sugar", 0.0625], ["basil", 0.25, "fresh, optional"], ["spaghetti", 1, "to serve (not in the original sauce recipe)"]],
    steps: ["You'll also need: 1 cup water; salt, black pepper and crushed red pepper flakes to taste.","Season the beef with salt and pepper, then brown it with the onion in a large skillet; drain off the fat.","Stir in the tomato sauce, tomato paste, Italian seasoning, parsley, garlic powder, red pepper flakes, Worcestershire and sugar.","Bring to a boil, then stir in the water.","Turn the heat down and simmer about 30 minutes.","Stir in chopped basil if using and serve over cooked spaghetti."],
  },
  {
    key: "fam-white-chicken-chili",
    name: "Creamy White Chicken Chili",
    mealTimes: ["dinner"],
    type: "Soup",
    feeds: 6,
    activeMinutes: 15,
    totalMinutes: 45,
    tags: ["stove top","crock pot"],
    url: "https://www.halfbakedharvest.com/creamy-white-chicken-chili/",
    lines: [["olive-oil", 2], ["onion", 1, "chopped"], ["garlic", 4, "minced"], ["poblano", 2, "seeded, chopped"], ["jalapeno", 1, "chopped"], ["cumin", 2], ["paprika", 1, "smoked"], ["chili-powder", 0.17, "½ tsp"], ["chicken-breast", 1], ["chicken-broth", 6], ["cream-cheese", 3, "room temperature"], ["white-beans", 1, "drained"], ["cheddar", 0.33], ["cilantro", 0.5, "chopped"], ["avocado", 1, "to serve"], ["cheddar", 0.5, "to serve"], ["plain-yogurt", 0.5, "to serve"], ["lime", 1, "zest and juice, to serve"]],
    steps: ["You'll also need: kosher salt and black pepper to taste.","Warm the oil in a big pot over medium heat and soften the onion for about 5 minutes.","Add the garlic, poblanos, jalapeño, cumin, paprika, chili powder, salt and pepper; cook 5-10 minutes until aromatic.","Add the chicken and broth, partly cover, and simmer on medium-low about 20 minutes until the chicken is done.","Lift out the chicken and shred it; briefly microwave the cream cheese to soften.","Whisk the cream cheese into the pot, then return the chicken with the beans and cheddar; cook 5-10 minutes until the cheese melts.","Take off the heat, stir in cilantro, and serve topped with avocado, cheese, yogurt and lime.","Slow cooker option: combine everything except beans, cheddar and cilantro and cook 6-7 hours on low (4-5 on high), then shred the chicken and stir those in."],
  },
  {
    key: "fam-taco-soup",
    name: "Taco Soup",
    mealTimes: ["dinner"],
    type: "Soup",
    feeds: 8,
    activeMinutes: 5,
    totalMinutes: 25,
    tags: ["stove top","freezer"],
    url: "https://tastesbetterfromscratch.com/taco-soup/",
    lines: [["ground-beef", 1, "lean"], ["garlic", 4, "minced"], ["chili-powder", 0.67, "2 tsp"], ["cumin", 1], ["salt", 1], ["oregano", 0.5], ["paprika", 0.5], ["onion-powder", 0.5], ["pepper", 0.5], ["crushed-tomatoes", 1, "28 oz, undrained"], ["green-chiles", 1], ["kidney-beans", 1, "rinsed and drained"], ["black-beans", 1, "rinsed and drained"], ["canned-corn", 1, "drained"], ["beef-broth", 2, "low-sodium"], ["tortilla-chips", 4, "crushed, to top"], ["sour-cream", 0.5, "to top"], ["cheddar", 1, "to top"], ["green-onions", 0.5, "to top"], ["avocado", 1, "to top"], ["cilantro", 0.25, "to top"]],
    steps: ["You'll also need: hot sauce, for topping.","Brown the ground beef in a soup pot or Dutch oven over medium heat and drain any fat.","Add the garlic, spices, tomatoes, green chiles, beans, corn and broth and stir well.","Bring to a boil, then lower the heat and simmer 20 minutes.","Serve with whichever toppings you like.","Slow cooker option: after browning the beef, put everything in the slow cooker on low for 4-6 hours."],
  },
  {
    key: "fam-chocolate-sheet-cake",
    name: "Chocolate Sheet Cake",
    mealTimes: ["dessert"],
    type: "Dessert",
    feeds: 15,
    activeMinutes: 10,
    totalMinutes: 30,
    tags: ["treat","oven","holiday"],
    url: "https://tastesbetterfromscratch.com/the-best-texas-sheet-cake/",
    lines: [["butter", 16, "cake"], ["cocoa", 3, "cake"], ["flour", 2], ["sugar", 2], ["baking-soda", 1], ["salt", 0.5], ["sour-cream", 0.5], ["eggs", 2], ["vanilla", 1], ["milk", 0.375, "frosting"], ["cocoa", 3, "frosting"], ["butter", 8, "frosting"], ["powdered-sugar", 3.75, "frosting"]],
    steps: ["You'll also need: 1 cup water (for the cake).","Heat the oven to 350°F and grease an 18x13-inch sheet pan.","Bring the water, butter and cocoa to a boil in a saucepan.","Meanwhile whisk the flour, sugar, baking soda and salt in one bowl, and the sour cream, eggs and vanilla in another; combine the two.","Pour the hot chocolate mixture into the batter and mix until smooth, then spread it evenly in the pan.","Bake 15-20 minutes until set.","While it bakes, boil the milk, cocoa and butter, take off the heat and beat in the powdered sugar until smooth.","Spread the hot frosting over the hot cake and let it set about 10 minutes before cutting."],
  },
  {
    key: "fam-garlic-green-beans",
    name: "Garlic Green Beans",
    mealTimes: ["side"],
    type: "Vegetable",
    feeds: 4,
    activeMinutes: 10,
    totalMinutes: 20,
    tags: ["stove top"],
    url: "https://www.allrecipes.com/recipe/230103/buttery-garlic-green-beans/",
    lines: [["fresh-green-beans", 1, "trimmed, snapped in half"], ["butter", 3], ["garlic", 3, "minced"], ["lemon-pepper", 0.125, "2 pinches"]],
    steps: ["You'll also need: salt to taste.","Put the beans in a large skillet, cover with water and bring to a boil.","Lower to medium-low and simmer about 5 minutes until just starting to soften, then drain.","Add the butter and stir for 2-3 minutes as it melts.","Add the garlic and cook 3-4 minutes until fragrant and soft.","Season with lemon pepper and salt."],
  },
  {
    key: "fam-chicken-marinade",
    name: "The Best Chicken Marinade",
    mealTimes: ["dinner"],
    type: "Meat",
    feeds: 6,
    activeMinutes: 10,
    totalMinutes: 265,
    tags: ["grill","make ahead"],
    url: "https://www.momontimeout.com/the-best-chicken-marinade-recipe/",
    lines: [["olive-oil", 8], ["balsamic", 8], ["soy-sauce", 4], ["worcestershire", 4], ["lemon-juice", 2], ["brown-sugar", 0.75], ["rosemary", 2], ["dijon", 2, "or spicy brown"], ["salt", 2], ["pepper", 1], ["garlic-powder", 2], ["chicken-breast", 3.5, "6 breasts, to marinate"]],
    steps: ["Whisk together everything except the chicken.","Set aside about 1/2 cup of the marinade for basting.","Seal the chicken and remaining marinade in a large zip-top bag and refrigerate 4 to 24 hours.","Heat the grill to medium-high and oil the grates; let excess marinade drip off the chicken.","Grill 5-6 minutes per side until cooked through, basting now and then with the reserved marinade.","Rest the chicken under foil at least 5 minutes. Optionally boil and reduce leftover reserved marinade into a sauce."],
  },
  {
    key: "fam-brigadeiro",
    name: "Brigadeiro (Brazilian Chocolate Truffles)",
    mealTimes: ["dessert"],
    type: "Dessert",
    feeds: 10,
    activeMinutes: 35,
    totalMinutes: 105,
    tags: ["treat","stove top","kid project"],
    url: "https://www.iheartbrazil.com/brigadeiro-recipe/",
    lines: [["condensed-milk", 1], ["cocoa", 3, "sifted"], ["butter", 1], ["sprinkles", 6, "for coating"]],
    steps: ["You'll also need: a pinch of salt.","Butter a plate and set it aside.","Cook the condensed milk, butter, cocoa and salt in a nonstick pan over medium heat, stirring constantly, for 10-12 minutes until a spatula dragged through leaves a trail that holds for a few seconds.","Spread the mixture on the buttered plate and chill about an hour.","Set out candy cups and a bowl of sprinkles.","With lightly wet hands, roll tablespoon-size balls, coat them in sprinkles and set each in a cup."],
  },
  {
    key: "fam-pudding-cookies",
    name: "Chocolate Chip Pudding Cookies",
    mealTimes: ["dessert"],
    type: "Dessert",
    feeds: 18,
    activeMinutes: 10,
    totalMinutes: 20,
    tags: ["treat","oven"],
    url: "https://www.sixsistersstuff.com/recipe/chocolate-chip-pudding-cookies-recipe/",
    lines: [["butter", 12, "softened"], ["brown-sugar", 0.75], ["sugar", 0.25], ["pudding-mix", 1, "3.4 oz instant vanilla"], ["eggs", 2], ["vanilla", 1], ["baking-soda", 1], ["flour", 2.25], ["chocolate-chips", 2]],
    steps: ["Preheat the oven to 350°F.","Cream the butter, both sugars and the pudding mix, then beat in the eggs and vanilla.","Stir the flour and baking soda together and mix into the dough just until combined; fold in the chocolate chips.","Shape 1-inch balls and set them on a greased or lined baking sheet.","Bake 8-10 minutes until lightly golden."],
  },
  {
    key: "fam-pb-no-bake-cookies",
    name: "Peanut Butter Chocolate No-Bake Cookies",
    mealTimes: ["dessert"],
    type: "Dessert",
    feeds: 20,
    activeMinutes: 10,
    totalMinutes: 40,
    tags: ["treat","no bake"],
    url: "https://www.foodnetwork.com/recipes/food-network-kitchen/peanut-butter-chocolate-no-bake-cookies-recipe-2015085",
    lines: [["sugar", 2], ["milk", 0.5], ["butter", 8], ["cocoa", 4], ["oats", 3, "old-fashioned"], ["peanut-butter", 16, "smooth"], ["vanilla", 3], ["salt", 0.25, "a large pinch"]],
    steps: ["Line a baking sheet with wax paper or parchment.","In a medium saucepan over medium heat, bring the sugar, milk, butter and cocoa to a boil, stirring now and then; boil 1 minute and take off the heat.","Stir in the oats, peanut butter, vanilla and salt.","Drop teaspoon-size mounds onto the sheet and let them set at room temperature, about 30 minutes.","Store refrigerated in an airtight container up to 3 days."],
  },
  {
    key: "fam-strawberry-topping",
    name: "Supreme Strawberry Topping",
    mealTimes: ["dessert","breakfast"],
    type: "Sauce",
    feeds: 4,
    activeMinutes: 15,
    totalMinutes: 35,
    tags: ["stove top"],
    url: "https://www.allrecipes.com/recipe/43914/supreme-strawberry-topping/",
    lines: [["strawberries", 2.25, "1 pint, hulled"], ["sugar", 0.33], ["vanilla", 1]],
    steps: ["Rinse and hull the strawberries, halving or roughly chopping any large ones.","Put the berries, sugar and vanilla in a saucepan over medium-high heat and stir now and then.","Once juice starts to form, keep stirring and crush some berries with a spoon to build the syrup; cook until thickened, about 15 minutes.","Take off the heat, blend roughly a third of the sauce until smooth, and stir it back in.","Keep refrigerated."],
  },
  {
    key: "fam-strawberry-crepes",
    name: "Creamy Strawberry Crepes",
    mealTimes: ["breakfast"],
    type: "Breakfast",
    feeds: 6,
    activeMinutes: 30,
    totalMinutes: 60,
    tags: ["stove top","holiday"],
    url: "https://www.allrecipes.com/recipe/143886/creamy-strawberry-crepes/",
    lines: [["eggs", 3, "batter"], ["milk", 0.5, "batter"], ["butter", 3, "melted, batter"], ["flour", 0.75, "batter"], ["salt", 0.5], ["cream-cheese", 8, "softened, filling"], ["powdered-sugar", 1.25, "sifted, filling"], ["lemon", 0.5, "1 tbsp juice and 1 tsp zest"], ["vanilla", 0.5], ["heavy-cream", 1, "whipped"], ["strawberries", 4, "sliced"]],
    steps: ["You'll also need: ½ cup water (for the batter).","Blend the eggs, milk, water, melted butter, flour and salt until smooth.","Beat the cream cheese, powdered sugar, lemon juice, zest and vanilla until smooth, then gently fold in the whipped cream.","Cook about 2 tbsp batter at a time in a lightly oiled nonstick pan over medium heat, swirling it thin; flip once set and browning at the edges.","Stack the cooked crepes under a damp towel.","Fill each crepe with strawberries and some of the cream filling, roll up, and top with a little more filling and berries."],
  },
  {
    key: "fam-brownies",
    name: "Brownie Recipe",
    mealTimes: ["dessert"],
    type: "Dessert",
    feeds: 16,
    activeMinutes: 5,
    totalMinutes: 45,
    tags: ["treat","oven"],
    url: "https://www.loveandlemons.com/brownies-recipe/",
    lines: [["sugar", 1.5], ["flour", 0.75], ["cocoa", 10.67, "⅔ cup, sifted"], ["powdered-sugar", 0.5], ["chocolate-chips", 0.5, "dark"], ["salt", 0.75], ["eggs", 2], ["vegetable-oil", 8, "canola, or olive oil"], ["vanilla", 0.5]],
    steps: ["You'll also need: 2 tablespoons water.","Heat the oven to 325°F; grease an 8x8 pan, line it with parchment and grease the paper.","Stir together the sugar, flour, cocoa, powdered sugar, chocolate chips and salt.","In a larger bowl whisk the eggs, oil, water and vanilla.","Add the dry mix to the wet and stir only until combined; spread the thick batter in the pan.","Bake 40–48 minutes, until a toothpick shows just a few moist crumbs.","Let cool completely before cutting into 16 squares."],
  },
  {
    key: "fam-maple-bacon-donuts",
    name: "Maple Bacon Donuts",
    mealTimes: ["breakfast"],
    type: "Breakfast",
    feeds: 6,
    activeMinutes: 75,
    totalMinutes: 90,
    tags: ["treat","stove top"],
    url: "https://www.bakedbyrachel.com/maple-bacon-donuts/",
    lines: [["milk", 0.75, "warmed to 115°F"], ["yeast", 1, "2¼ tsp"], ["sugar", 0.27, "1 tsp + ¼ cup, divided"], ["flour", 2.5], ["salt", 0.5], ["shortening", 3], ["vanilla", 1], ["eggs", 1], ["vegetable-oil", 4, "for frying — about ¼ of the 1 cup used is absorbed (estimate)"], ["powdered-sugar", 2, "icing"], ["maple-syrup", 0.25, "icing"], ["bacon", 8, "cooked, chopped"]],
    steps: ["You'll also need: 2–3 tablespoons water (for the icing).","Stir the warm milk, yeast and 1 tsp sugar together and let it foam for 5–10 minutes.","In a stand mixer combine the rest of the sugar with the flour, salt, shortening, egg and vanilla, then stream in the yeast mixture and mix into a soft dough.","Put the dough in a greased bowl, cover and let it double in a warm spot, about 45 minutes.","Roll out 1/4–1/2 inch thick, cut donuts, set on a greased parchment-lined sheet and let rise again while the oil heats to 325°F.","Fry a few at a time until golden on both sides and drain on a rack or paper towels.","Whisk the powdered sugar, maple syrup and water into an icing, dip the cooled donuts, and scatter bacon on top right away."],
  },
  {
    key: "fam-spinach-artichoke-dip",
    name: "The Best Spinach Artichoke Dip",
    mealTimes: ["other"],
    type: "Snack",
    feeds: 9,
    activeMinutes: 20,
    totalMinutes: 55,
    tags: ["oven","holiday"],
    url: "https://www.melskitchencafe.com/the-best-spinach-artichoke-dip/",
    lines: [["heavy-cream", 1.5, "or half-and-half or milk"], ["flour", 0.125], ["garlic-powder", 0.5], ["salt", 1], ["pepper", 0.25], ["cream-cheese", 8, "softened"], ["artichokes", 2, "drained, chopped"], ["hot-sauce", 0.5, "optional"], ["parmesan", 16, "1 cup grated"], ["mozzarella", 1, "or Monterey Jack"], ["frozen-spinach", 16, "thawed, squeezed dry"], ["tortilla-chips", 13, "or bread, to serve"]],
    steps: ["Heat the oven to 350°F and grease a 9x13 (or similar) baking dish.","Whisk the cream or milk with the flour, garlic powder, salt and pepper in a microwave-safe bowl; microwave in 1-minute bursts, whisking between each, until thick like warm pudding (4–5 min).","Whisk in the cream cheese until mostly smooth, then add the artichokes, hot sauce, cheeses and finally the spinach, crumbling it in.","Spread in the dish and bake 25–30 minutes until bubbly and golden.","Serve warm with bread or tortilla chips."],
  },
  {
    key: "fam-shrapnel-dip",
    name: "Amazing Shrapnel Dip",
    mealTimes: ["other"],
    type: "Snack",
    feeds: 6,
    activeMinutes: 20,
    totalMinutes: 20,
    tags: ["no bake","make ahead"],
    url: "https://www.melskitchencafe.com/amazing-shrapnel-dip/",
    lines: [["white-beans", 1, "drained and rinsed"], ["black-beans", 1, "drained and rinsed"], ["canned-corn", 0.75, "11 oz, drained"], ["avocado", 1, "diced"], ["bell-pepper", 1, "red, diced"], ["tomato", 1, "diced"], ["red-onion", 0.125, "2 tbsp chopped"], ["cilantro", 0.15, "chopped"], ["italian-dressing", 5.33, "⅓ cup"], ["lime", 0.5, "squeeze"], ["tortilla-chips", 13, "to serve"]],
    steps: ["You'll also need: salt and pepper to taste.","Drain the beans and corn together, rinse briefly, and get them as dry as possible (salad spinner or paper towels); tip into a serving bowl.","Add the avocado, bell pepper, tomatoes, red onion and cilantro.","Pour over the Italian dressing and fold gently until everything is coated.","Finish with a squeeze of lime, season with salt and pepper, and serve right away with chips.","If making ahead, hold back the avocado and stir it in just before serving."],
  },
  {
    key: "fam-caramel-sauce",
    name: "Divine Caramel Sauce",
    mealTimes: ["dessert"],
    type: "Sauce",
    feeds: 12,
    activeMinutes: 5,
    totalMinutes: 25,
    tags: ["stove top"],
    url: "https://www.melskitchencafe.com/divine-caramel-sauce/",
    lines: [["sugar", 1], ["butter", 8, "salted, in 8 pieces"], ["heavy-cream", 0.5], ["vanilla", 1], ["salt", 0.0625, "a pinch"]],
    steps: ["You'll also need: ¼ cup water.","Gently combine the sugar and water in a small heavy saucepan without splashing the sides.","Warm over low heat, stirring slowly, until the sugar is mostly dissolved.","Raise to medium, bring to a boil, cover and boil 2 minutes; uncover and keep boiling without stirring, brushing any crystals off the pan sides with a wet pastry brush.","Cook until the syrup is a deep amber, about 5–7 minutes more, watching closely.","Off the heat, stir in the butter until melted, then the cream (rewarm gently if lumpy), then the vanilla and salt.","Cool to warm, then jar and refrigerate; rewarm to serve."],
  },
  {
    key: "fam-dulce-de-leche",
    name: "DIY Dulce de Leche",
    mealTimes: ["dessert"],
    type: "Sauce",
    feeds: 12,
    activeMinutes: 5,
    totalMinutes: 545,
    tags: ["crock pot","make ahead"],
    url: "https://www.melskitchencafe.com/diy-dulce-de-leche/",
    lines: [["condensed-milk", 2], ["vanilla", 1, "optional"]],
    steps: ["You'll also need: water to cover the jars; three ½-pint canning jars with lids and rings.","Divide the condensed milk evenly among the three jars, wipe the rims and sides clean, and screw the lids on tight.","Set the jars in a slow cooker (upright or on their sides) and cover with water by about an inch.","Cook on low for 8–9 hours until the contents are a deep golden brown.","Lift the jars out carefully and let cool; stir some vanilla into each jar if you like.","Refrigerate for up to about a month; warm gently to drizzle over ice cream or crepes, or use as a dip for fruit."],
  },
  {
    key: "fam-ny-cheesecake",
    name: "Chantal's New York Cheesecake",
    mealTimes: ["dessert"],
    type: "Dessert",
    feeds: 12,
    activeMinutes: 30,
    totalMinutes: 450,
    tags: ["treat","oven","holiday","make ahead"],
    url: "https://www.allrecipes.com/recipe/8350/chantals-new-york-cheesecake/",
    lines: [["graham-crackers", 15, "crushed, crust"], ["butter", 2, "melted, crust"], ["cream-cheese", 32, "4 packages"], ["sugar", 1.5], ["milk", 0.75], ["eggs", 4], ["sour-cream", 1], ["vanilla", 3], ["flour", 0.25]],
    steps: ["Heat the oven to 350°F and grease a 9-inch springform pan.","Mix the graham crumbs with the melted butter and press into the bottom of the pan.","Beat the cream cheese and sugar until smooth, add the milk, then the eggs one by one, mixing only until each is incorporated; finish with the sour cream, vanilla and flour.","Pour the filling over the crust and bake for 1 hour.","Switch the oven off and leave the cheesecake inside with the door shut for 5–6 hours to prevent cracks.","Refrigerate until serving."],
  },
  {
    key: "fam-homemade-oreos",
    name: "Homemade Oreos",
    mealTimes: ["dessert"],
    type: "Dessert",
    feeds: 6,
    activeMinutes: 20,
    totalMinutes: 80,
    tags: ["treat","oven","kid project"],
    url: "https://www.yourcupofcake.com/2010/11/homemade-oreos.html",
    lines: [["cake-mix", 1, "devil's food"], ["eggs", 2], ["vegetable-oil", 5.33, "⅓ cup"], ["cream-cheese", 4, "softened, filling"], ["butter", 4, "softened, filling"], ["powdered-sugar", 1.5, "filling"], ["vanilla", 0.5]],
    steps: ["Heat the oven to 350F and line baking sheets with parchment.","Stir the cake mix, eggs and oil together into a thick dough.","Roll into balls a bit smaller than a golf ball, about 12 per sheet, and press each flat.","Bake 7-10 minutes; rest 3 minutes on the sheet, then move to a rack to cool fully.","Beat the cream cheese and butter about 3 minutes, then mix in the vanilla and enough powdered sugar to make a thick filling.","Spread filling on half the cookies, top with the rest, and chill at least an hour before serving."],
  },
  {
    key: "fam-strawberry-pie",
    name: "Fresh Strawberry Pie",
    mealTimes: ["dessert"],
    type: "Dessert",
    feeds: 8,
    activeMinutes: 15,
    totalMinutes: 210,
    tags: ["treat","make ahead"],
    url: "https://www.allrecipes.com/recipe/15836/strawberry-pie-ii/",
    lines: [["strawberries", 4, "1 quart, hulled"], ["pie-crust", 1, "9-inch, baked"], ["sugar", 1], ["cornstarch", 3], ["heavy-cream", 0.5, "whipped, to top"]],
    steps: ["You'll also need: ¾ cup water.","Put half the strawberries into the baked pie shell and the other half into a saucepan.","Add the sugar to the pan and bring to a boil over medium heat, stirring often.","Whisk the cornstarch into the water, stir it into the boiling berries, then lower the heat and simmer about 10 minutes, stirring, until thick.","Pour the hot mixture over the berries in the crust and refrigerate at least 3 hours until set.","Whip the cream to soft peaks and serve a spoonful on each slice."],
  },
  {
    key: "fam-tomato-onion-salad",
    name: "Portuguese Tomato Onion Salad",
    mealTimes: ["lunch","side"],
    type: "Salad",
    feeds: 6,
    activeMinutes: 5,
    totalMinutes: 5,
    tags: ["no bake"],
    url: "https://www.savoringthethyme.com/2011/05/simple-tomato-onion-salad-recipe-straight-from-portugal/",
    lines: [["tomato", 3, "ripe, in sections"], ["onion", 0.75, "sweet, sliced"], ["olive-oil", 2, "to taste"], ["rice-vinegar", 1, "to taste"], ["salt", 0.5], ["pepper", 0.25]],
    steps: ["Cut the tomato into wedges and thinly slice the onion.","Put both in a bowl.","Dress with a drizzle of olive oil and rice wine vinegar, season with salt and pepper, and serve."],
  },
  {
    key: "fam-chicken-enchiladas",
    name: "Chicken Enchiladas",
    mealTimes: ["dinner"],
    type: "Mexican",
    feeds: 8,
    activeMinutes: 20,
    totalMinutes: 45,
    tags: ["oven"],
    url: "https://www.myrecipes.com/recipe/chicken-enchiladas-50400000118610/",
    lines: [["corn-tortillas", 8, "6-inch"], ["onion", 0.1, "1½ tbsp chopped"], ["cilantro", 0.1, "chopped"], ["jalapeno", 1, "seeded, chopped"], ["rotisserie-chicken", 1, "3 cups shredded breast"], ["enchilada-sauce", 3, "divided"], ["cheddar", 1.5, "reduced-fat sharp"], ["tomato", 1, "diced"], ["black-olives", 0.33, "sliced"], ["iceberg", 4, "shredded"]],
    steps: ["You'll also need: cooking spray.","Heat the oven to 350F; wrap the tortillas in foil and warm them in the oven for 15 minutes.","Meanwhile, saute the onion, cilantro and jalapeño in a sprayed nonstick skillet until soft, then add the chicken and one can of sauce and cook 5 minutes.","Fill each tortilla with the chicken mixture, roll up and lay seam-side down in a 13x9 dish.","Warm the other two cans of sauce, pour over the enchiladas and scatter the cheese on top.","Bake about 10 minutes until hot and melted, top with tomato and olives, and serve on the shredded lettuce."],
  },
  {
    key: "fam-seven-layer-dip",
    name: "7-Layer Bean Dip",
    mealTimes: ["other"],
    type: "Snack",
    feeds: 10,
    activeMinutes: 10,
    totalMinutes: 10,
    tags: ["no bake","make ahead","holiday"],
    url: "https://www.lifesambrosia.com/seven-layer-dip/",
    lines: [["refried-beans", 1, "spicy"], ["guacamole", 1], ["mayo", 8], ["sour-cream", 0.5], ["taco-seasoning", 0.33, "1 tbsp"], ["cheddar", 1], ["green-onions", 0.3, "2, diced"], ["black-olives", 0.5, "4 oz can, sliced"], ["tomato", 2, "seeded, diced"], ["tortilla-chips", 13, "to serve"]],
    steps: ["Stir the mayonnaise, sour cream and taco seasoning together in a small bowl.","Spread the refried beans over the bottom of a serving dish.","Layer the seasoned sour cream mixture over the beans, then the guacamole.","Top with the cheese, then the green onions, olives and tomatoes.","Cover and chill at least 30 minutes if you have time, then serve with chips."],
  },
  {
    key: "fam-cup-cube-can",
    name: "A Cup, a Cube, a Can",
    mealTimes: ["dessert"],
    type: "Dessert",
    feeds: 8,
    activeMinutes: 10,
    totalMinutes: 55,
    tags: ["treat","oven"],
    lines: [["flour", 1], ["sugar", 1], ["butter", 8, "1 cube"], ["pie-filling", 1, "peach, cherry or apple"], ["milk", 1], ["baking-powder", 2], ["salt", 0.25]],
    steps: ["Heat the oven to 350F. Put the butter in an 8x8 or similar baking dish and set it in the oven until melted.","Whisk the flour, sugar, baking powder and salt, then stir in the milk just until smooth.","Pour the batter over the melted butter without stirring.","Spoon the pie filling evenly over the batter, again without stirring.","Bake 40-45 minutes until the batter has puffed up around the fruit and the edges are deep golden. Serve warm, with ice cream if you like."],
  },
  {
    key: "fam-texas-pulled-pork",
    name: "Slow Cooker Texas Pulled Pork",
    mealTimes: ["dinner"],
    type: "Crock Pot",
    feeds: 8,
    activeMinutes: 15,
    totalMinutes: 315,
    tags: ["crock pot","make ahead"],
    url: "https://www.allrecipes.com/recipe/92462/slow-cooker-texas-pulled-pork/",
    lines: [["vegetable-oil", 0.33], ["pork-shoulder", 4], ["bbq-sauce", 1], ["cider-vinegar", 8], ["chicken-broth", 0.5], ["brown-sugar", 0.25], ["mustard", 1], ["worcestershire", 1], ["chili-powder", 1], ["onion", 1, "extra large, chopped"], ["garlic", 2, "crushed"], ["thyme", 1.5], ["hamburger-buns", 8, "split"], ["butter", 2, "for the buns"]],
    steps: ["Oil the bottom of the slow cooker, add the pork, and pour over the barbecue sauce, vinegar and broth.","Stir in the brown sugar, mustard, Worcestershire, chili powder, onion, garlic and thyme.","Cover and cook on High 5-6 hours or Low 10-12 hours, until the pork pulls apart easily.","Lift out the pork, shred it with two forks, and stir it back into the juices.","Butter the cut sides of the buns, toast them butter-side down in a skillet until golden, and fill with the pork."],
  },
  {
    key: "fam-dorito-salad",
    name: "Dorito Salad",
    mealTimes: ["dinner"],
    type: "Salad",
    feeds: 6,
    activeMinutes: 10,
    totalMinutes: 30,
    tags: ["kid favorite","stove top"],
    url: "https://www.garnishandglaze.com/dorito-taco-salad-recipe/",
    lines: [["vegetable-oil", 0.67], ["onion", 0.5, "chopped"], ["ground-beef", 1], ["taco-seasoning", 1.33, "¼ cup"], ["romaine", 8, "3 hearts, chopped"], ["kidney-beans", 1, "drained and rinsed"], ["cheddar", 0.75], ["frozen-corn", 1, "fire-roasted"], ["grape-tomatoes", 1, "halved"], ["black-olives", 0.5, "sliced"], ["avocado", 1, "diced"], ["doritos", 3, "Nacho, broken"], ["catalina", 12]],
    steps: ["You'll also need: ¾ cup water (for the taco meat).","Soften the onion in the oil in a skillet over medium heat for about 5 minutes, then push it to the sides.","Raise the heat and brown the beef well, breaking it up as it sears, then drain off the fat.","Stir in the taco seasoning and water, cover and simmer on low 10-15 minutes, then let it cool a little.","Toss the lettuce, beans, cheese, corn, tomatoes and olives in a large bowl.","Just before serving, add the Doritos, beef, avocado and dressing, toss to coat and serve."],
  },
  {
    key: "fam-buttermilk-syrup",
    name: "Grandma's Buttermilk Syrup",
    mealTimes: ["breakfast"],
    type: "Sauce",
    feeds: 6,
    activeMinutes: 5,
    totalMinutes: 10,
    tags: ["stove top"],
    url: "https://www.allrecipes.com/recipe/239478/grandmas-buttermilk-syrup/",
    lines: [["sugar", 1], ["buttermilk", 0.5], ["butter", 8], ["baking-soda", 1], ["vanilla", 1]],
    steps: ["Warm the sugar, buttermilk and butter in a saucepan over medium heat until it comes to a boil, about 5 minutes.","Take it off the heat and stir in the baking soda and vanilla. It will foam up, so use a roomy pan.","Serve warm over pancakes or waffles."],
  },
  {
    key: "fam-waffles",
    name: "Waffles",
    mealTimes: ["breakfast"],
    type: "Breakfast",
    feeds: 5,
    activeMinutes: 10,
    totalMinutes: 25,
    tags: ["kid favorite","freezer"],
    url: "https://www.allrecipes.com/recipe/20513/classic-waffles/",
    lines: [["flour", 2], ["salt", 1], ["baking-powder", 4], ["sugar", 0.125], ["eggs", 2], ["milk", 1.5, "warm"], ["butter", 5.33, "melted"], ["vanilla", 1]],
    steps: ["Heat the waffle iron.","Whisk the flour, salt, baking powder and sugar in a large bowl.","In another bowl beat the eggs, then mix in the warm milk, melted butter and vanilla.","Pour the wet mixture into the dry and beat just until blended.","Ladle batter onto the hot iron and cook until golden and crisp. Serve right away."],
  },
  {
    key: "fam-gv-garlic-breadsticks",
    name: "Garlic Breadsticks (Great Value, frozen)",
    mealTimes: ["side"],
    type: "Bread",
    feeds: 8,
    activeMinutes: 2,
    totalMinutes: 20,
    tags: ["oven"],
    lines: [["gv-garlic-breadsticks", 8, "one bag"]],
    steps: ["Bake from frozen on a sheet pan as the bag says, usually 400°F for 10–12 minutes."],
  },
  {
    key: "fam-gv-garlic-knots",
    name: "Garlic Knots (Great Value, frozen)",
    mealTimes: ["side"],
    type: "Bread",
    feeds: 6,
    activeMinutes: 2,
    totalMinutes: 20,
    tags: ["oven"],
    lines: [["gv-garlic-knots", 12, "one bag"]],
    steps: ["Bake from frozen as the bag says, usually 400°F for 10–13 minutes, until golden."],
  },
  {
    key: "fam-rhodes-rolls",
    name: "Rhodes Dinner Rolls (frozen)",
    mealTimes: ["side"],
    type: "Bread",
    feeds: 7,
    activeMinutes: 5,
    totalMinutes: 240,
    tags: ["oven","make ahead","holiday"],
    lines: [["rhodes-rolls", 14, "two each"]],
    steps: ["Set the frozen rolls on a greased pan, cover with greased plastic wrap, and let them thaw and rise 3–5 hours, until doubled.","Bake at 350°F for 15–20 minutes, until golden. Brush with butter if you like."],
  },
  {
    key: "fam-rhodes-cinnamon-rolls",
    name: "Rhodes Cinnamon Rolls (frozen)",
    mealTimes: ["dessert","breakfast"],
    type: "Dessert",
    feeds: 12,
    activeMinutes: 5,
    totalMinutes: 240,
    tags: ["oven","treat","make ahead"],
    lines: [["rhodes-cinnamon-rolls", 12, "one bag, frosting included"]],
    steps: ["Set the frozen rolls in a greased 9×13, cover, and let them rise until doubled, 3–4 hours (or overnight in the fridge).","Bake at 350°F for 20–25 minutes.","Spread the frosting packet over them while they are warm."],
  },
  {
    key: "fam-blt-croissants",
    name: "BLTs on Croissants",
    mealTimes: ["lunch"],
    type: "Sandwich",
    feeds: 7,
    activeMinutes: 20,
    totalMinutes: 20,
    tags: ["stove top"],
    lines: [["croissants", 7, "split"], ["bacon", 21, "3 slices each, cooked crisp"], ["romaine", 3.5, "leaves"], ["tomato", 3, "sliced"], ["mayo", 7]],
    steps: ["Cook the bacon until crisp and drain it.","Split the croissants and spread each with mayonnaise.","Layer lettuce, tomato and three slices of bacon in each."],
  },
  {
    key: "fam-walking-tacos",
    name: "Walking Tacos",
    mealTimes: ["dinner","lunch"],
    type: "Mexican",
    feeds: 7,
    activeMinutes: 15,
    totalMinutes: 20,
    tags: ["kid favorite","stove top"],
    lines: [["chip-snack-bags", 7, "Fritos or Doritos, one each"], ["ground-beef", 1.5], ["taco-seasoning", 1], ["cheddar", 1.5], ["iceberg", 2, "shredded"], ["tomato", 2, "diced"], ["sour-cream", 0.5], ["salsa", 0.5]],
    steps: ["Brown the beef, drain, and stir in the taco seasoning with a little water; simmer 5 minutes.","Crush each bag of chips lightly and cut it open along the side.","Everyone spoons meat and toppings straight into their own bag and eats it with a fork."],
  },
  {
    key: "fam-tacos",
    name: "Tacos",
    mealTimes: ["dinner"],
    type: "Mexican",
    feeds: 7,
    activeMinutes: 20,
    totalMinutes: 20,
    tags: ["kid favorite","stove top"],
    lines: [["ground-beef", 2], ["taco-seasoning", 2], ["small-tortillas", 14, "or hard shells"], ["cheddar", 2], ["iceberg", 3, "shredded"], ["tomato", 3, "diced"], ["sour-cream", 1], ["salsa", 1]],
    steps: ["Brown the beef and drain it. Stir in the seasoning with ⅔ cup water per packet and simmer 5 minutes.","Warm the tortillas.","Set out the toppings and let everyone build their own."],
  },
  {
    key: "fam-banana-pb-smoothie",
    name: "Banana Peanut Butter Smoothie",
    mealTimes: ["breakfast","other"],
    type: "Drink",
    feeds: 4,
    activeMinutes: 5,
    totalMinutes: 5,
    tags: ["no bake","kid favorite"],
    lines: [["banana", 3, "frozen is best"], ["peanut-butter", 6], ["milk", 3], ["yogurt", 1, "vanilla"], ["honey", 2]],
    steps: ["Blend everything with a handful of ice until smooth.","Add a splash more milk if it is too thick."],
  },
];

/**
 * Starter recipes the family's own supersede. Each becomes another *version*
 * of the family's recipe rather than being deleted, so it is still one tap
 * away on the meal's sheet.
 */
const REGROUP: Readonly<Record<string, string>> = {
  "teriyaki-chicken": "fam-baked-teriyaki-chicken",
  "chocolate-chip-cookies": "fam-best-chocolate-chip-cookies",
  "chicken-pot-pie": "fam-chicken-pot-pie",
  "haystacks": "fam-hawaiian-haystacks",
  "alfredo": "fam-alfredo",
  "spaghetti": "fam-spaghetti-sauce",
  "white-chicken-chili": "fam-white-chicken-chili",
  "taco-soup": "fam-taco-soup",
  "no-bake-cookies": "fam-pb-no-bake-cookies",
  "brownies-box": "fam-brownies",
  "enchiladas": "fam-chicken-enchiladas",
  "pulled-pork": "fam-texas-pulled-pork",
  "waffles": "fam-waffles",
  "tacos-beef": "fam-tacos"
};

export const FAMILY_FAVORITES_BATCH: SeedBatch = {
  id: "family-favorites-2026-09",
  ingredients: INGREDIENTS,
  recipes: RECIPES,
  regroup: REGROUP,
};
