/**
 * The starter catalog: the ingredients the family buys, what they cost, and
 * the meals they make.
 *
 * ---------------------------------------------------------------------------
 * WHAT THIS FILE IS FOR
 * ---------------------------------------------------------------------------
 * The Meals page is only useful with meals on it, and a family should not have
 * to type seventy recipes into a phone before it is. So the first time the
 * page is opened against an empty database, everything below is written into
 * it (see `ensureMealsSeeded` in `lib/meals/store.ts`), and from then on the
 * database is the catalog: parents add, edit and re-price from `/meals/admin`,
 * and nothing here is read again except as the offline fallback.
 *
 * Changing a recipe here therefore does **not** change it in a database that
 * has already been seeded — the same rule, for the same reason, as the Bored
 * Page's ideas. Edit it from the admin screen instead.
 *
 * ---------------------------------------------------------------------------
 * THE NUMBERS
 * ---------------------------------------------------------------------------
 * Prices are researched estimates for late 2026, not receipts: every one is
 * seeded with `estimated: true`, and the Prices tab says so until a parent
 * confirms or corrects it at the shop. Nutrition is per one of the
 * ingredient's units, from typical package labels — estimates too, and the
 * page labels them that way.
 *
 * Quantities are in each ingredient's own unit. Butter is in tablespoons (a
 * stick is 8), sugar in cups (2 tbsp is 0.125) — the page converts back to
 * whichever reads best when it shows them.
 *
 * Keys are permanent. They are hashed into the documents' ids (see
 * `seedId`), which is what makes seeding safe to repeat and what lets the
 * offline fallback agree with the database about which meal is which. Rename
 * the `name`, never the key.
 */

import type { MealTime, MealType } from "./meals";

/** [calories, carbs g, sugar g, protein g, fat g] per unit. */
type NutritionTuple = readonly [number, number, number, number, number];

export type SeedIngredient = {
  key: string;
  name: string;
  unit: string;
  packLabel: string;
  packUnits: number;
  /** Store name → price of one pack. */
  prices: Readonly<Record<string, number>>;
  nutrition: NutritionTuple | null;
};

export type SeedRecipe = {
  key: string;
  name: string;
  mealTimes: readonly MealTime[];
  type: MealType;
  feeds: number;
  activeMinutes: number;
  totalMinutes: number;
  tags: readonly string[];
  /** [ingredient key, quantity in its unit, note?] */
  lines: readonly (readonly [string, number] | readonly [string, number, string])[];
  steps: readonly string[];
  /** Key of the recipe this is another version of. */
  variantOf?: string;
};

/** Walmart and Broulim's, the two shops almost everything is priced at. */
function ing(
  key: string,
  name: string,
  unit: string,
  packLabel: string,
  packUnits: number,
  walmart: number,
  broulims: number,
  nutrition: NutritionTuple | null,
): SeedIngredient {
  return {
    key,
    name,
    unit,
    packLabel,
    packUnits,
    prices: { Walmart: walmart, "Broulim's": broulims },
    nutrition,
  };
}

/** Something bought from a named vendor rather than off a grocery shelf. */
function vendor(
  key: string,
  name: string,
  unit: string,
  packLabel: string,
  prices: Readonly<Record<string, number>>,
  nutrition: NutritionTuple | null,
): SeedIngredient {
  return { key, name, unit, packLabel, packUnits: 1, prices, nutrition };
}

/* -------------------------------------------------------------------------- */
/* Ingredients                                                                 */
/* -------------------------------------------------------------------------- */

export const SEED_INGREDIENTS: readonly SeedIngredient[] = [
  // --- Dairy and eggs -----------------------------------------------------
  ing("eggs", "Eggs", "egg", "18 ct carton", 18, 3.97, 4.99, [72, 0.4, 0.2, 6.3, 4.8]),
  ing("milk", "Milk, 2%", "cup", "1 gal jug", 16, 3.12, 3.49, [122, 12, 12, 8, 4.8]),
  ing("butter", "Butter", "tbsp", "1 lb (4 sticks)", 32, 4.12, 4.99, [102, 0, 0, 0.1, 11.5]),
  ing("cheddar", "Cheddar cheese, shredded", "cup", "2 lb bag", 8, 8.47, 9.99, [455, 1.4, 0.4, 28, 37]),
  ing("mozzarella", "Mozzarella, shredded", "cup", "2 lb bag", 8, 8.47, 9.99, [336, 2.4, 1, 25, 25]),
  ing("parmesan", "Parmesan, grated", "tbsp", "8 oz canister", 45, 3.48, 4.29, [22, 0.2, 0, 1.9, 1.4]),
  ing("american-cheese", "American cheese slices", "slice", "16 slice pack", 16, 2.48, 3.29, [60, 1.5, 1, 3, 4.5]),
  ing("cream-cheese", "Cream cheese", "oz", "8 oz block", 8, 1.98, 2.49, [99, 1.6, 1, 1.7, 9.8]),
  ing("sour-cream", "Sour cream", "cup", "16 oz tub", 2, 1.97, 2.49, [445, 10, 7.7, 5.4, 45]),
  ing("heavy-cream", "Heavy whipping cream", "cup", "1 pint carton", 2, 3.12, 3.99, [821, 6.6, 6.6, 6.8, 88]),
  ing("yogurt", "Vanilla yogurt", "cup", "32 oz tub", 4, 2.24, 2.99, [208, 34, 34, 12, 3]),
  ing("ricotta", "Ricotta cheese", "cup", "15 oz tub", 1.75, 3.48, 3.99, [428, 7.5, 0.6, 28, 32]),

  // --- Meat and fish ------------------------------------------------------
  ing("ground-beef", "Ground beef, 80/20", "lb", "3 lb pack", 3, 16.47, 17.97, [1120, 0, 0, 76, 88]),
  ing("chicken-breast", "Chicken breasts, boneless", "lb", "3 lb pack", 3, 9.91, 10.47, [544, 0, 0, 102, 12]),
  ing("chicken-thighs", "Chicken thighs, boneless", "lb", "3 lb pack", 3, 9.47, 10.49, [544, 0, 0, 90, 18]),
  ing("drumsticks", "Chicken drumsticks", "lb", "5 lb family pack", 5, 7.35, 8.95, [550, 0, 0, 65, 30]),
  ing("pork-shoulder", "Pork shoulder roast", "lb", "4 lb roast", 4, 10.72, 11.96, [1070, 0, 0, 77, 83]),
  ing("chuck-roast", "Beef chuck roast", "lb", "3 lb roast", 3, 21.87, 23.97, [1130, 0, 0, 85, 86]),
  ing("sausage", "Breakfast sausage", "lb", "1 lb roll", 1, 3.47, 3.99, [1520, 0, 0, 64, 136]),
  ing("smoked-sausage", "Smoked sausage", "package", "14 oz package", 1, 3.48, 3.99, [1260, 14, 7, 49, 112]),
  ing("bacon", "Bacon", "slice", "16 oz pack", 16, 4.97, 6.99, [43, 0.1, 0, 3, 3.3]),
  ing("ham", "Ham, sliced deli", "oz", "16 oz pack", 16, 4.48, 5.99, [30, 1, 1, 5, 1]),
  ing("hot-dogs", "Hot dogs", "hot dog", "8 ct pack", 8, 1.48, 1.99, [150, 2, 1, 5, 13]),
  ing("pepperoni", "Pepperoni", "oz", "6 oz bag", 6, 2.97, 3.49, [140, 0, 0, 6, 13]),
  ing("salmon", "Salmon fillets, frozen", "lb", "2 lb bag", 2, 13.98, 15.98, [940, 0, 0, 91, 62]),
  ing("tuna", "Tuna, chunk light", "can", "5 oz can", 1, 0.98, 1.39, [100, 0, 0, 22, 1]),
  ing("fish-sticks", "Fish sticks", "stick", "44 ct box", 44, 6.48, 7.99, [50, 4.5, 0.3, 2.5, 2.5]),
  ing("nuggets", "Chicken nuggets, frozen", "nugget", "32 oz bag (~50)", 50, 7.47, 8.99, [45, 3, 0.1, 2.6, 2.6]),
  ing("meatballs", "Meatballs, frozen", "meatball", "32 oz bag (~64)", 64, 7.47, 8.99, [47, 1.5, 0.5, 2.3, 3.5]),
  {
    key: "rotisserie-chicken",
    name: "Rotisserie chicken",
    unit: "chicken",
    packLabel: "whole chicken",
    packUnits: 1,
    prices: { Walmart: 6.97, "Broulim's": 7.99, Costco: 4.99 },
    nutrition: [1500, 0, 0, 200, 75],
  },

  // --- Produce ------------------------------------------------------------
  ing("potatoes", "Russet potatoes", "lb", "10 lb bag", 10, 4.97, 5.99, [350, 79, 3, 9.5, 0.4]),
  ing("onion", "Yellow onion", "onion", "3 lb bag (~6)", 6, 2.97, 3.49, [44, 10, 4.7, 1.2, 0.1]),
  ing("garlic", "Garlic", "clove", "3 bulb pack (~30 cloves)", 30, 1.47, 1.99, [4.5, 1, 0, 0.2, 0]),
  ing("carrots", "Carrots", "cup", "2 lb bag", 7, 1.68, 1.99, [52, 12, 6, 1.2, 0.3]),
  ing("celery", "Celery", "stalk", "1 bunch (~9 stalks)", 9, 1.48, 1.99, [6, 1.2, 0.5, 0.3, 0.1]),
  ing("bell-pepper", "Bell pepper", "pepper", "each", 1, 0.84, 1.29, [30, 7, 4, 1, 0.3]),
  ing("broccoli", "Broccoli florets", "cup", "12 oz bag", 4, 1.97, 2.49, [31, 6, 1.5, 2.6, 0.3]),
  ing("romaine", "Romaine hearts", "cup", "3 ct pack", 11, 2.98, 3.99, [8, 1.5, 0.6, 0.6, 0.1]),
  ing("iceberg", "Iceberg lettuce", "cup", "1 head", 7.5, 1.97, 2.29, [10, 2, 1.4, 0.6, 0.1]),
  ing("tomato", "Roma tomatoes", "tomato", "each", 1, 0.24, 0.33, [11, 2.4, 1.6, 0.5, 0.1]),
  ing("cucumber", "Cucumber", "cucumber", "each", 1, 0.68, 0.99, [45, 11, 5, 2, 0.3]),
  ing("zucchini", "Zucchini", "zucchini", "each", 1, 0.84, 0.99, [33, 6, 5, 2.4, 0.6]),
  ing("mushrooms", "Mushrooms, sliced", "cup", "8 oz pack", 3, 1.97, 2.49, [15, 2.3, 1.4, 2.2, 0.2]),
  ing("banana", "Bananas", "banana", "each", 1, 0.26, 0.35, [105, 27, 14, 1.3, 0.4]),
  ing("apple", "Apples", "apple", "3 lb bag (~8)", 8, 3.97, 4.99, [95, 25, 19, 0.5, 0.3]),
  ing("lemon", "Lemons", "lemon", "each", 1, 0.58, 0.79, [17, 5.4, 1.5, 0.6, 0.2]),
  ing("lime", "Limes", "lime", "each", 1, 0.34, 0.5, [20, 7, 1.1, 0.5, 0.1]),
  ing("strawberries", "Strawberries", "cup", "1 lb clamshell", 3, 2.97, 3.49, [53, 13, 8, 1.1, 0.5]),
  ing("grapes", "Grapes", "cup", "2 lb bag", 6, 4.96, 5.98, [104, 27, 23, 1.1, 0.2]),
  ing("avocado", "Avocados", "avocado", "each", 1, 0.88, 1.25, [240, 13, 1, 3, 22]),
  ing("cilantro", "Cilantro", "bunch", "1 bunch", 1, 0.78, 0.99, [10, 1.6, 0.4, 0.9, 0.2]),
  ing("green-onions", "Green onions", "bunch", "1 bunch", 1, 0.64, 0.99, [32, 7, 2.3, 1.8, 0.2]),
  ing("jalapeno", "Jalapeños", "pepper", "each", 1, 0.12, 0.15, [4, 0.9, 0.6, 0.1, 0.1]),

  // --- Frozen -------------------------------------------------------------
  ing("frozen-corn", "Corn, frozen", "cup", "12 oz bag", 2.5, 1.12, 1.49, [125, 27, 4, 4, 1]),
  ing("frozen-peas", "Peas, frozen", "cup", "12 oz bag", 2.5, 1.12, 1.49, [110, 20, 7, 7, 0.5]),
  ing("mixed-veg", "Mixed vegetables, frozen", "cup", "12 oz bag", 2.5, 1.12, 1.49, [90, 18, 4, 4, 0.3]),
  ing("stir-fry-veg", "Stir-fry vegetables, frozen", "cup", "16 oz bag", 4.5, 1.97, 2.49, [40, 8, 3, 2, 0.2]),
  ing("green-beans", "Green beans, frozen", "cup", "12 oz bag", 3, 1.12, 1.49, [35, 8, 3, 2, 0.1]),
  ing("hash-browns", "Hash browns, shredded frozen", "cup", "30 oz bag", 10, 2.97, 3.49, [70, 15, 0.3, 1.7, 0.1]),
  ing("fries", "French fries, frozen", "serving", "32 oz bag (~11 servings)", 11, 2.97, 3.49, [120, 19, 0, 2, 4.5]),
  ing("berries", "Mixed berries, frozen", "cup", "48 oz bag", 9.5, 9.24, 11.49, [70, 17, 11, 1, 0.5]),
  ing("ice-cream", "Vanilla ice cream", "cup", "48 oz tub", 6, 3.47, 4.99, [274, 32, 28, 4.6, 14.5]),
  ing("whipped-topping", "Whipped topping", "tub", "8 oz tub", 1, 1.48, 2.29, [625, 55, 42, 0, 38]),
  ing("frozen-pizza", "Frozen pepperoni pizza, 12\"", "pizza", "each", 1, 4.47, 5.99, [1280, 132, 16, 52, 60]),

  // --- Cans, jars and sauces ----------------------------------------------
  ing("diced-tomatoes", "Diced tomatoes", "can", "14.5 oz can", 1, 0.88, 1.19, [88, 18, 11, 4, 0.5]),
  ing("tomato-sauce", "Tomato sauce", "can", "15 oz can", 1, 0.84, 0.99, [70, 16, 11, 3, 0.5]),
  ing("pasta-sauce", "Spaghetti sauce", "jar", "24 oz jar", 1, 1.67, 2.49, [385, 60, 40, 10, 12]),
  ing("pizza-sauce", "Pizza sauce", "jar", "14 oz jar", 1, 1.48, 1.99, [140, 24, 14, 4, 4]),
  ing("black-beans", "Black beans", "can", "15 oz can", 1, 0.78, 0.99, [350, 63, 1, 22, 1]),
  ing("pinto-beans", "Pinto beans", "can", "15 oz can", 1, 0.78, 0.99, [350, 63, 2, 21, 2]),
  ing("kidney-beans", "Kidney beans", "can", "15 oz can", 1, 0.78, 0.99, [350, 60, 4, 24, 1]),
  ing("white-beans", "Great Northern beans", "can", "15 oz can", 1, 0.88, 1.19, [350, 63, 2, 24, 1]),
  ing("refried-beans", "Refried beans", "can", "16 oz can", 1, 1.12, 1.39, [385, 63, 3, 21, 5]),
  ing("green-chiles", "Diced green chiles", "can", "4 oz can", 1, 0.98, 1.29, [20, 4, 2, 1, 0]),
  ing("enchilada-sauce", "Red enchilada sauce", "can", "10 oz can", 1, 1.42, 1.99, [70, 12, 3, 2, 2]),
  ing("cream-of-chicken", "Cream of chicken soup", "can", "10.5 oz can", 1, 0.98, 1.29, [300, 23, 2, 6, 20]),
  ing("cream-of-mushroom", "Cream of mushroom soup", "can", "10.5 oz can", 1, 0.98, 1.29, [250, 22, 2, 4, 16]),
  ing("tomato-soup", "Tomato soup, condensed", "can", "10.75 oz can", 1, 0.84, 1.25, [225, 50, 30, 5, 0]),
  ing("sloppy-joe-sauce", "Sloppy joe sauce", "can", "15 oz can", 1, 1.48, 1.99, [280, 56, 42, 7, 0]),
  ing("chicken-broth", "Chicken broth", "cup", "32 oz carton", 4, 1.38, 1.99, [10, 1, 0.5, 1, 0.5]),
  ing("beef-broth", "Beef broth", "cup", "32 oz carton", 4, 1.38, 1.99, [15, 1, 1, 2, 0.5]),
  ing("pineapple", "Pineapple chunks", "can", "20 oz can", 1, 1.48, 1.99, [270, 70, 60, 2, 0]),
  ing("mandarins", "Mandarin oranges", "can", "15 oz can", 1, 1.12, 1.29, [240, 58, 54, 2, 0]),
  ing("salsa", "Salsa", "cup", "16 oz jar", 2, 1.78, 2.49, [70, 16, 8, 3, 0.4]),
  ing("bbq-sauce", "BBQ sauce", "cup", "18 oz bottle", 1.75, 1.18, 1.99, [560, 136, 112, 0, 1]),
  ing("teriyaki", "Teriyaki sauce", "cup", "20 oz bottle", 2.25, 2.12, 2.99, [240, 48, 32, 16, 0]),
  ing("ketchup", "Ketchup", "tbsp", "38 oz bottle", 64, 2.47, 3.49, [20, 5, 4, 0.2, 0]),
  ing("mustard", "Yellow mustard", "tbsp", "20 oz bottle", 38, 0.98, 1.49, [9, 0.6, 0, 0.6, 0.4]),
  ing("mayo", "Mayonnaise", "tbsp", "30 oz jar", 60, 3.68, 4.99, [90, 0, 0, 0, 10]),
  ing("ranch", "Ranch dressing", "tbsp", "16 oz bottle", 30, 1.98, 2.99, [65, 1, 0.5, 0.2, 7]),
  ing("soy-sauce", "Soy sauce", "tbsp", "15 oz bottle", 30, 1.88, 2.49, [10, 1, 0.4, 1.3, 0]),
  ing("honey", "Honey", "tbsp", "12 oz bottle", 16, 3.72, 4.49, [64, 17, 17, 0, 0]),
  ing("syrup", "Pancake syrup", "cup", "24 oz bottle", 3, 2.12, 2.99, [840, 208, 128, 0, 0]),
  ing("peanut-butter", "Peanut butter", "tbsp", "40 oz jar", 70, 4.98, 6.49, [95, 3.5, 1.5, 3.5, 8]),
  ing("jam", "Strawberry jam", "tbsp", "30 oz jar", 42, 2.98, 3.49, [50, 13, 12, 0, 0]),
  ing("chocolate-syrup", "Chocolate syrup", "tbsp", "24 oz bottle", 36, 2.24, 2.99, [50, 12, 10, 0.4, 0.2]),
  ing("frosting", "Chocolate frosting", "tub", "16 oz tub", 1, 1.68, 2.49, [1680, 264, 240, 0, 66]),

  // --- Oils, baking and spices --------------------------------------------
  ing("olive-oil", "Olive oil", "tbsp", "17 oz bottle", 34, 5.97, 6.99, [120, 0, 0, 0, 14]),
  ing("vegetable-oil", "Vegetable oil", "tbsp", "48 oz bottle", 96, 3.48, 4.49, [120, 0, 0, 0, 14]),
  ing("flour", "Flour, all-purpose", "cup", "5 lb bag", 18, 2.72, 3.29, [455, 95, 0.3, 13, 1.2]),
  ing("sugar", "Sugar", "cup", "4 lb bag", 9, 3.24, 3.99, [774, 200, 200, 0, 0]),
  ing("brown-sugar", "Brown sugar", "cup", "2 lb bag", 4, 1.97, 2.49, [829, 214, 213, 0, 0]),
  ing("powdered-sugar", "Powdered sugar", "cup", "2 lb bag", 7.5, 1.97, 2.49, [467, 120, 117, 0, 0]),
  ing("baking-powder", "Baking powder", "tsp", "8.1 oz can", 50, 1.28, 1.79, [2, 1.3, 0, 0, 0]),
  ing("baking-soda", "Baking soda", "tsp", "1 lb box", 98, 0.88, 1.29, [0, 0, 0, 0, 0]),
  ing("yeast", "Active dry yeast", "packet", "3 ct strip", 3, 1.62, 2.29, [21, 2.7, 0, 2.8, 0.3]),
  ing("cornstarch", "Cornstarch", "tbsp", "16 oz box", 57, 1.12, 1.49, [30, 7, 0, 0, 0]),
  ing("cocoa", "Cocoa powder", "tbsp", "8 oz canister", 42, 3.68, 4.49, [12, 3, 0.1, 1, 0.7]),
  ing("chocolate-chips", "Chocolate chips", "cup", "12 oz bag", 2, 2.62, 3.49, [805, 107, 93, 7, 48]),
  ing("marshmallows", "Mini marshmallows", "cup", "10 oz bag", 5.5, 1.28, 1.79, [159, 41, 29, 0.9, 0.1]),
  ing("vanilla", "Vanilla extract", "tsp", "8 oz bottle", 48, 1.24, 1.99, [2, 0.5, 0.5, 0, 0]),
  ing("salt", "Salt", "tsp", "26 oz canister", 122, 0.58, 0.99, [0, 0, 0, 0, 0]),
  ing("pepper", "Black pepper", "tsp", "3 oz shaker", 37, 1.98, 2.49, [6, 1.5, 0, 0.2, 0.1]),
  ing("cinnamon", "Cinnamon", "tsp", "2.4 oz jar", 26, 1.24, 1.99, [6, 2, 0, 0.1, 0]),
  ing("cumin", "Ground cumin", "tsp", "2 oz jar", 28, 1.98, 2.49, [8, 0.9, 0, 0.4, 0.5]),
  ing("chili-powder", "Chili powder", "tbsp", "2.5 oz jar", 9, 1.24, 1.79, [24, 4, 0.6, 1, 1.2]),
  ing("garlic-powder", "Garlic powder", "tsp", "3.4 oz jar", 31, 1.24, 1.99, [10, 2, 0.1, 0.5, 0]),
  ing("italian-seasoning", "Italian seasoning", "tsp", "0.9 oz jar", 25, 0.98, 1.49, [3, 0.6, 0, 0.1, 0.1]),
  ing("taco-seasoning", "Taco seasoning", "packet", "1 oz packet", 1, 0.54, 0.89, [120, 24, 6, 0, 0]),
  ing("ranch-mix", "Ranch seasoning mix", "packet", "1 oz packet", 1, 1.28, 1.99, [60, 12, 0, 0, 0]),
  ing("gravy-mix", "Brown gravy mix", "packet", "0.87 oz packet", 1, 0.64, 0.99, [70, 12, 0, 2, 2]),
  ing("pancake-mix", "Pancake mix, complete", "cup", "32 oz box", 7.5, 2.12, 2.99, [450, 90, 12, 12, 4.5]),
  ing("brownie-mix", "Brownie mix", "box", "18.3 oz box", 1, 1.48, 2.49, [1960, 392, 280, 16, 30]),
  ing("cake-mix", "Chocolate cake mix", "box", "15.25 oz box", 1, 1.28, 1.99, [1680, 340, 190, 16, 30]),

  // --- Grains, bread and pasta --------------------------------------------
  ing("oats", "Rolled oats", "cup", "42 oz canister", 15, 3.48, 4.49, [300, 54, 1, 10, 5]),
  ing("rice", "White rice, long grain", "cup dry", "5 lb bag", 12, 3.48, 4.49, [675, 148, 0.2, 13, 1.2]),
  ing("cereal", "Toasted oat cereal", "cup", "18 oz box", 18, 2.98, 3.99, [100, 20, 1.3, 3.4, 2]),
  ing("crisp-rice", "Crisp rice cereal", "cup", "12 oz box", 13, 2.72, 3.79, [105, 24, 3, 2, 0]),
  ing("raisins", "Raisins", "cup", "12 oz box", 2, 2.48, 2.99, [490, 130, 97, 5, 0.8]),
  ing("popcorn", "Popcorn kernels", "cup", "30 oz jar", 4.25, 2.98, 3.49, [760, 150, 1, 25, 9]),
  ing("bread", "Sandwich bread", "slice", "20 oz loaf (~22 slices)", 22, 1.42, 2.49, [70, 13, 1.5, 2, 1]),
  ing("hamburger-buns", "Hamburger buns", "bun", "8 ct pack", 8, 1.38, 1.99, [120, 22, 3, 4, 1.5]),
  ing("hot-dog-buns", "Hot dog buns", "bun", "8 ct pack", 8, 1.38, 1.99, [110, 20, 3, 4, 1.5]),
  ing("french-bread", "French bread", "loaf", "1 loaf", 1, 1.48, 2.49, [1100, 210, 8, 40, 8]),
  ing("bagels", "Plain bagels", "bagel", "6 ct bag", 6, 2.48, 2.99, [270, 53, 6, 10, 1.5]),
  ing("large-tortillas", "Flour tortillas, 10\"", "tortilla", "10 ct pack", 10, 2.38, 2.99, [210, 35, 2, 6, 5]),
  ing("small-tortillas", "Flour tortillas, 8\"", "tortilla", "20 ct pack", 20, 2.62, 3.49, [140, 24, 1, 4, 3.5]),
  ing("taco-shells", "Hard taco shells", "shell", "18 ct box", 18, 1.84, 2.49, [50, 6.5, 0, 0.8, 2.5]),
  ing("tortilla-chips", "Tortilla chips", "oz", "13 oz bag", 13, 2.12, 3.49, [140, 19, 0, 2, 7]),
  ing("spaghetti", "Spaghetti", "lb", "1 lb box", 1, 1.12, 1.29, [1600, 336, 12, 56, 8]),
  ing("fettuccine", "Fettuccine", "lb", "1 lb box", 1, 1.12, 1.29, [1600, 336, 12, 56, 8]),
  ing("elbow-macaroni", "Elbow macaroni", "lb", "1 lb box", 1, 1.12, 1.29, [1600, 336, 12, 56, 8]),
  ing("lasagna-noodles", "Lasagna noodles", "lb", "1 lb box", 1, 1.48, 1.99, [1600, 336, 12, 56, 8]),
  ing("egg-noodles", "Egg noodles", "oz", "12 oz bag", 12, 1.98, 2.49, [110, 20, 1, 4, 1.3]),
  ing("mac-box", "Macaroni & cheese, boxed", "box", "7.25 oz box", 1, 0.58, 0.99, [725, 138, 17, 29, 8]),
  ing("pie-crust", "Refrigerated pie crust", "crust", "2 ct box", 2, 2.48, 3.29, [880, 96, 8, 8, 52]),
  ing("biscuits", "Refrigerated biscuits", "can", "8 ct can", 1, 1.48, 2.29, [1360, 176, 24, 32, 56]),

  // --- Bought ready-made --------------------------------------------------
  vendor(
    "little-caesars",
    "Little Caesars pepperoni pizza",
    "pizza",
    "large",
    { "Little Caesars": 7.99 },
    [2240, 256, 24, 96, 88],
  ),
  vendor(
    "dominos",
    "Domino's large pepperoni pizza",
    "pizza",
    "large, carryout",
    { "Domino's": 9.99 },
    [2400, 264, 24, 100, 104],
  ),
  vendor(
    "papa-murphys",
    "Papa Murphy's large pepperoni pizza",
    "pizza",
    "large, take and bake",
    { "Papa Murphy's": 13.99 },
    [2640, 272, 24, 112, 120],
  ),
];

/* -------------------------------------------------------------------------- */
/* Costco                                                                      */
/* -------------------------------------------------------------------------- */

/**
 * Costco's price for the staples it sells, and **its own pack** — which is
 * almost never the size the other two stores sell. [price, pack, units in the
 * pack], the units being the ingredient's own (cups, tbsp, lb…).
 *
 * Estimates for late 2026, like every other starter price. Costco only wins a
 * line on the shopping list when the week needs enough to make the big pack
 * the smaller bill — see `bestBuy` in `lib/meals/costing.ts`.
 */
export const SEED_COSTCO: Readonly<Record<string, readonly [number, string, number]>> = {
  eggs: [9.99, "60 ct (5 dozen)", 60],
  milk: [6.49, "2 × 1 gal", 32],
  butter: [14.99, "4 lb (16 sticks)", 128],
  cheddar: [16.99, "5 lb bag", 20],
  mozzarella: [16.49, "5 lb bag", 20],
  "cream-cheese": [10.99, "6 × 8 oz", 48],
  "heavy-cream": [7.99, "½ gallon", 8],
  "ground-beef": [24.95, "5 lb pack", 5],
  "chicken-breast": [20.94, "6 lb pack", 6],
  "chicken-thighs": [17.45, "5 lb pack", 5],
  bacon: [17.99, "4 × 1 lb", 64],
  salmon: [26.99, "3 lb bag", 3],
  tuna: [15.99, "8 × 7 oz cans", 11.2],
  potatoes: [7.99, "15 lb bag", 15],
  onion: [7.99, "10 lb bag (~20)", 20],
  carrots: [8.49, "10 lb bag", 35],
  banana: [1.99, "3 lb bunch (~7)", 7],
  strawberries: [9.99, "4 lb clamshell", 12],
  avocado: [6.99, "bag of 5", 5],
  romaine: [5.49, "6 ct pack", 22],
  broccoli: [6.99, "3 lb bag", 16],
  berries: [13.49, "4 lb bag", 12.5],
  flour: [9.99, "25 lb bag", 90],
  sugar: [8.99, "10 lb bag", 22.5],
  rice: [18.99, "25 lb bag", 60],
  oats: [10.99, "10 lb bag", 56],
  "olive-oil": [18.99, "2 L bottle", 135],
  "peanut-butter": [11.99, "2 × 40 oz", 140],
  "tortilla-chips": [6.49, "40 oz bag", 40],
  spaghetti: [11.99, "8 × 1 lb", 8],
  "pasta-sauce": [9.99, "3 × 32 oz", 4],
  "black-beans": [8.99, "8 × 15 oz", 8],
  "diced-tomatoes": [8.49, "8 × 14.5 oz", 8],
  "chicken-broth": [11.99, "6 × 32 oz", 24],
  "chocolate-chips": [13.99, "4.5 lb bag", 12],
  ketchup: [8.99, "3 × 44 oz", 222],
  mayo: [8.99, "64 oz jar", 128],
  honey: [14.49, "3 lb jar", 64],
};

/* -------------------------------------------------------------------------- */
/* Recipes                                                                     */
/* -------------------------------------------------------------------------- */

export const SEED_RECIPES: readonly SeedRecipe[] = [
  /* --- Breakfast ------------------------------------------------------- */
  {
    key: "pancakes-mix",
    name: "Pancakes (from mix)",
    mealTimes: ["breakfast"],
    type: "Breakfast",
    feeds: 7,
    activeMinutes: 20,
    totalMinutes: 25,
    tags: ["kid favorite", "stove top"],
    lines: [
      ["pancake-mix", 4.5],
      ["butter", 3, "for the griddle"],
      ["syrup", 1],
    ],
    steps: [
      "Whisk the mix with about 3 cups of water until just combined — lumps are fine.",
      "Heat a griddle to medium and butter it lightly.",
      "Pour ¼ cup per pancake; flip when the bubbles pop and the edges look dry.",
      "Serve with syrup.",
    ],
  },
  {
    key: "pancakes-scratch",
    name: "Pancakes (from scratch)",
    variantOf: "pancakes-mix",
    mealTimes: ["breakfast"],
    type: "Breakfast",
    feeds: 7,
    activeMinutes: 25,
    totalMinutes: 30,
    tags: ["kid favorite", "stove top"],
    lines: [
      ["flour", 3],
      ["sugar", 0.25],
      ["baking-powder", 6],
      ["salt", 1],
      ["milk", 2.75],
      ["eggs", 2],
      ["butter", 6, "melted, plus more for the griddle"],
      ["vanilla", 1],
      ["syrup", 1],
    ],
    steps: [
      "Whisk the flour, sugar, baking powder and salt in a big bowl.",
      "Whisk the milk, eggs, melted butter and vanilla in another, then pour into the dry and stir until just combined.",
      "Cook ¼ cup at a time on a buttered griddle over medium heat, flipping once.",
      "Serve with syrup.",
    ],
  },
  {
    key: "waffles",
    name: "Waffles",
    mealTimes: ["breakfast"],
    type: "Breakfast",
    feeds: 7,
    activeMinutes: 30,
    totalMinutes: 35,
    tags: ["kid favorite", "freezer"],
    lines: [
      ["flour", 3],
      ["baking-powder", 5],
      ["sugar", 0.1875],
      ["salt", 1],
      ["eggs", 3],
      ["milk", 2.75],
      ["vegetable-oil", 8],
      ["vanilla", 1],
      ["syrup", 1],
      ["strawberries", 2, "sliced, on top"],
    ],
    steps: [
      "Heat the waffle iron.",
      "Whisk the dry ingredients; whisk the eggs, milk, oil and vanilla; combine until just mixed.",
      "Cook in the greased iron until golden. Extras freeze well and reheat in the toaster.",
      "Serve with syrup and strawberries.",
    ],
  },
  {
    key: "french-toast",
    name: "French Toast",
    mealTimes: ["breakfast"],
    type: "Breakfast",
    feeds: 7,
    activeMinutes: 25,
    totalMinutes: 25,
    tags: ["kid favorite", "stove top"],
    lines: [
      ["bread", 14],
      ["eggs", 6],
      ["milk", 1.5],
      ["cinnamon", 1],
      ["vanilla", 1],
      ["sugar", 0.125],
      ["butter", 3, "for the griddle"],
      ["syrup", 1],
    ],
    steps: [
      "Whisk the eggs, milk, cinnamon, vanilla and sugar in a shallow dish.",
      "Dip each slice for a couple of seconds a side.",
      "Cook on a buttered griddle over medium heat until golden, about 3 minutes a side.",
      "Serve with syrup.",
    ],
  },
  {
    key: "scrambled-eggs",
    name: "Scrambled Eggs & Toast",
    mealTimes: ["breakfast"],
    type: "Breakfast",
    feeds: 7,
    activeMinutes: 15,
    totalMinutes: 15,
    tags: ["stove top"],
    lines: [
      ["eggs", 14],
      ["milk", 0.25],
      ["cheddar", 0.5],
      ["butter", 5, "some for the pan, the rest for the toast"],
      ["bread", 14],
      ["salt", 0.5],
      ["pepper", 0.25],
    ],
    steps: [
      "Whisk the eggs with the milk, salt and pepper.",
      "Melt a tablespoon of butter in a big non-stick pan over medium-low heat.",
      "Pour in the eggs and stir slowly until just set; fold in the cheese.",
      "Toast and butter the bread while the eggs cook.",
    ],
  },
  {
    key: "breakfast-burritos",
    name: "Breakfast Burritos",
    mealTimes: ["breakfast"],
    type: "Breakfast",
    feeds: 10,
    activeMinutes: 35,
    totalMinutes: 40,
    tags: ["freezer", "make ahead", "stove top"],
    lines: [
      ["eggs", 12],
      ["sausage", 1],
      ["hash-browns", 3],
      ["cheddar", 1.5],
      ["large-tortillas", 10],
      ["salsa", 1],
      ["salt", 0.5],
    ],
    steps: [
      "Brown the sausage and drain it. Cook the hash browns crisp in the same pan.",
      "Scramble the eggs with the salt until just set.",
      "Fill each tortilla with egg, sausage, potatoes and cheese, then roll up.",
      "Serve with salsa. To freeze, wrap each in foil; reheat from frozen at 375°F for 25 minutes.",
    ],
  },
  {
    key: "egg-bake",
    name: "Sausage Egg Bake",
    mealTimes: ["breakfast"],
    type: "Breakfast",
    feeds: 10,
    activeMinutes: 20,
    totalMinutes: 70,
    tags: ["make ahead", "holiday", "oven"],
    lines: [
      ["sausage", 1],
      ["bread", 8, "cubed"],
      ["cheddar", 2],
      ["eggs", 12],
      ["milk", 2],
      ["salt", 1],
      ["pepper", 0.5],
    ],
    steps: [
      "Brown and drain the sausage.",
      "Spread the bread cubes in a greased 9×13; top with the sausage and cheese.",
      "Whisk the eggs, milk, salt and pepper and pour over. (It can sit in the fridge overnight here.)",
      "Bake at 350°F for 45–50 minutes, until the middle is set.",
    ],
  },
  {
    key: "oatmeal",
    name: "Brown Sugar Oatmeal",
    mealTimes: ["breakfast"],
    type: "Breakfast",
    feeds: 7,
    activeMinutes: 5,
    totalMinutes: 15,
    tags: ["stove top"],
    lines: [
      ["oats", 4],
      ["milk", 2],
      ["brown-sugar", 0.5],
      ["cinnamon", 1],
      ["raisins", 0.5],
      ["salt", 0.5],
    ],
    steps: [
      "Bring 6 cups of water, the milk and the salt to a simmer.",
      "Stir in the oats and cook 5 minutes, stirring now and then.",
      "Stir in the brown sugar and cinnamon; top with raisins.",
    ],
  },
  {
    key: "cereal",
    name: "Cereal & Bananas",
    mealTimes: ["breakfast"],
    type: "Breakfast",
    feeds: 7,
    activeMinutes: 5,
    totalMinutes: 5,
    tags: ["kid favorite", "no bake"],
    lines: [
      ["cereal", 10],
      ["milk", 6],
      ["banana", 4, "sliced"],
    ],
    steps: ["Bowls, cereal, milk, sliced banana on top."],
  },
  {
    key: "smoothies",
    name: "Berry Smoothies",
    mealTimes: ["breakfast", "other"],
    type: "Drink",
    feeds: 7,
    activeMinutes: 10,
    totalMinutes: 10,
    tags: ["no bake", "kid project"],
    lines: [
      ["berries", 4],
      ["banana", 3],
      ["yogurt", 3],
      ["milk", 2],
      ["honey", 2],
    ],
    steps: [
      "Blend everything until smooth, in two batches if the blender is small.",
      "Add a splash more milk if it is too thick to pour.",
    ],
  },
  {
    key: "german-pancakes",
    name: "German Pancakes",
    mealTimes: ["breakfast"],
    type: "Breakfast",
    feeds: 7,
    activeMinutes: 10,
    totalMinutes: 30,
    tags: ["kid favorite", "oven"],
    lines: [
      ["butter", 8],
      ["eggs", 12],
      ["milk", 2],
      ["flour", 2],
      ["salt", 0.5],
      ["powdered-sugar", 0.25],
      ["syrup", 0.5],
    ],
    steps: [
      "Heat the oven to 425°F. Melt the butter in a 9×13 in the oven.",
      "Blend the eggs, milk, flour and salt until smooth.",
      "Pour into the hot pan and bake 20 minutes, until puffed and golden. Don't open the oven early.",
      "Dust with powdered sugar; serve with syrup or lemon.",
    ],
  },
  {
    key: "biscuits-gravy",
    name: "Biscuits & Gravy",
    mealTimes: ["breakfast"],
    type: "Breakfast",
    feeds: 8,
    activeMinutes: 20,
    totalMinutes: 25,
    tags: ["stove top", "oven"],
    lines: [
      ["biscuits", 2],
      ["sausage", 1],
      ["flour", 0.33],
      ["milk", 3],
      ["pepper", 1],
      ["salt", 0.5],
    ],
    steps: [
      "Bake the biscuits as the can says.",
      "Brown the sausage in a big skillet; don't drain.",
      "Sprinkle the flour over and stir for a minute, then pour in the milk slowly, stirring.",
      "Simmer until thick; season with the pepper and salt. Spoon over split biscuits.",
    ],
  },

  /* --- Lunch ----------------------------------------------------------- */
  {
    key: "grilled-cheese",
    name: "Grilled Cheese & Tomato Soup",
    mealTimes: ["lunch", "dinner"],
    type: "Sandwich",
    feeds: 7,
    activeMinutes: 20,
    totalMinutes: 20,
    tags: ["kid favorite", "stove top"],
    lines: [
      ["bread", 14],
      ["american-cheese", 14],
      ["butter", 5],
      ["tomato-soup", 3],
    ],
    steps: [
      "Heat the soup with 3 cans of water (or milk) in a pot.",
      "Butter the outsides of the bread; put two slices of cheese inside each sandwich.",
      "Cook on a griddle over medium heat until golden on both sides.",
    ],
  },
  {
    key: "pbj",
    name: "PB&J Sandwiches",
    mealTimes: ["lunch"],
    type: "Sandwich",
    feeds: 7,
    activeMinutes: 10,
    totalMinutes: 10,
    tags: ["no bake", "kid project"],
    lines: [
      ["bread", 14],
      ["peanut-butter", 14],
      ["jam", 7],
      ["apple", 3, "sliced, on the side"],
    ],
    steps: ["Two tablespoons of peanut butter and one of jam per sandwich.", "Slice the apples to go with."],
  },
  {
    key: "quesadillas",
    name: "Cheese Quesadillas",
    mealTimes: ["lunch", "dinner"],
    type: "Mexican",
    feeds: 7,
    activeMinutes: 15,
    totalMinutes: 15,
    tags: ["kid favorite", "stove top"],
    lines: [
      ["small-tortillas", 10],
      ["cheddar", 3.5],
      ["salsa", 1],
      ["sour-cream", 0.5],
    ],
    steps: [
      "Sprinkle cheese over half of each tortilla and fold.",
      "Cook in a dry skillet over medium heat until crisp and melted, 2 minutes a side.",
      "Cut into wedges; serve with salsa and sour cream.",
    ],
  },
  {
    key: "chicken-quesadillas",
    name: "Chicken Quesadillas",
    variantOf: "quesadillas",
    mealTimes: ["lunch", "dinner"],
    type: "Mexican",
    feeds: 7,
    activeMinutes: 20,
    totalMinutes: 20,
    tags: ["stove top"],
    lines: [
      ["small-tortillas", 10],
      ["cheddar", 3],
      ["rotisserie-chicken", 1, "shredded"],
      ["salsa", 1],
      ["sour-cream", 0.5],
    ],
    steps: [
      "Shred the chicken.",
      "Fill half of each tortilla with cheese and chicken, fold, and cook in a dry skillet until crisp.",
      "Serve with salsa and sour cream.",
    ],
  },
  {
    key: "ham-sandwiches",
    name: "Ham & Cheese Sandwiches",
    mealTimes: ["lunch"],
    type: "Sandwich",
    feeds: 7,
    activeMinutes: 10,
    totalMinutes: 10,
    tags: ["no bake"],
    lines: [
      ["bread", 14],
      ["ham", 14],
      ["american-cheese", 7],
      ["mayo", 7],
      ["mustard", 3],
      ["iceberg", 3],
      ["tomato", 2, "sliced"],
    ],
    steps: ["Two ounces of ham and a slice of cheese per sandwich, with lettuce and tomato."],
  },
  {
    key: "chicken-noodle-soup",
    name: "Chicken Noodle Soup",
    mealTimes: ["lunch", "dinner"],
    type: "Soup",
    feeds: 8,
    activeMinutes: 20,
    totalMinutes: 45,
    tags: ["stove top", "freezer"],
    lines: [
      ["butter", 2],
      ["onion", 1, "diced"],
      ["carrots", 2, "sliced"],
      ["celery", 3, "sliced"],
      ["garlic", 2, "minced"],
      ["chicken-broth", 10],
      ["chicken-breast", 1.5],
      ["egg-noodles", 12],
      ["italian-seasoning", 1],
      ["salt", 1],
      ["pepper", 0.5],
    ],
    steps: [
      "Soften the onion, carrots and celery in the butter, 5 minutes. Add the garlic for a minute.",
      "Add the broth, whole chicken breasts and seasoning; simmer 20 minutes.",
      "Lift out the chicken, shred it and return it. Add the noodles and cook until tender.",
      "Taste for salt.",
    ],
  },
  {
    key: "tuna-melts",
    name: "Tuna Melts",
    mealTimes: ["lunch"],
    type: "Sandwich",
    feeds: 7,
    activeMinutes: 15,
    totalMinutes: 20,
    tags: ["stove top"],
    lines: [
      ["tuna", 4, "drained"],
      ["mayo", 6],
      ["celery", 2, "diced"],
      ["bread", 14],
      ["cheddar", 1.5],
      ["butter", 3],
    ],
    steps: [
      "Mix the tuna, mayo and celery.",
      "Spread on bread, top with cheese and the second slice; butter the outsides.",
      "Grill until golden and melted.",
    ],
  },
  {
    key: "pizza-bagels",
    name: "Pizza Bagels",
    mealTimes: ["lunch"],
    type: "Pizza",
    feeds: 7,
    activeMinutes: 10,
    totalMinutes: 20,
    tags: ["kid project", "oven"],
    lines: [
      ["bagels", 8, "split"],
      ["pizza-sauce", 1],
      ["mozzarella", 3],
      ["pepperoni", 4],
    ],
    steps: [
      "Heat the oven to 400°F. Lay the bagel halves on a sheet pan.",
      "Everyone builds their own: sauce, cheese, pepperoni.",
      "Bake 8–10 minutes, until bubbling.",
    ],
  },
  {
    key: "nachos",
    name: "Nachos (Basic)",
    mealTimes: ["lunch", "other"],
    type: "Mexican",
    feeds: 7,
    activeMinutes: 10,
    totalMinutes: 15,
    tags: ["oven", "microwave"],
    lines: [
      ["tortilla-chips", 13],
      ["refried-beans", 1],
      ["cheddar", 3],
      ["salsa", 1],
      ["sour-cream", 0.5],
      ["jalapeno", 2, "sliced, optional"],
    ],
    steps: [
      "Spread chips on a sheet pan; dot with warmed beans and cover with cheese.",
      "Bake at 400°F for 5–7 minutes.",
      "Top with salsa, sour cream and jalapeños.",
    ],
  },
  {
    key: "mac-box",
    name: "Mac & Cheese (boxed)",
    mealTimes: ["lunch", "dinner"],
    type: "Pasta",
    feeds: 7,
    activeMinutes: 5,
    totalMinutes: 15,
    tags: ["kid favorite", "stove top"],
    lines: [
      ["mac-box", 4],
      ["butter", 8],
      ["milk", 1],
    ],
    steps: ["Boil the macaroni as the box says, drain, and stir in the cheese packets, butter and milk."],
  },
  {
    key: "mac-homemade",
    name: "Mac & Cheese (homemade)",
    variantOf: "mac-box",
    mealTimes: ["lunch", "dinner"],
    type: "Pasta",
    feeds: 7,
    activeMinutes: 20,
    totalMinutes: 30,
    tags: ["kid favorite", "stove top"],
    lines: [
      ["elbow-macaroni", 1],
      ["butter", 4],
      ["flour", 0.25],
      ["milk", 3],
      ["cheddar", 3],
      ["salt", 1],
      ["pepper", 0.25],
    ],
    steps: [
      "Cook the macaroni; drain.",
      "Melt the butter, whisk in the flour for a minute, then slowly whisk in the milk and simmer until thick.",
      "Off the heat, stir in the cheese, salt and pepper, then the macaroni.",
    ],
  },
  {
    key: "hot-dogs",
    name: "Hot Dogs & Chips",
    mealTimes: ["lunch", "dinner"],
    type: "Kid",
    feeds: 8,
    activeMinutes: 10,
    totalMinutes: 15,
    tags: ["grill", "kid favorite"],
    lines: [
      ["hot-dogs", 16],
      ["hot-dog-buns", 16],
      ["ketchup", 8],
      ["mustard", 4],
      ["tortilla-chips", 10],
    ],
    steps: ["Grill or boil the hot dogs. Buns, ketchup, mustard, chips on the side."],
  },
  {
    key: "chicken-salad-sandwiches",
    name: "Chicken Salad Sandwiches",
    mealTimes: ["lunch"],
    type: "Sandwich",
    feeds: 7,
    activeMinutes: 20,
    totalMinutes: 20,
    tags: ["no bake", "make ahead"],
    lines: [
      ["rotisserie-chicken", 1, "shredded"],
      ["mayo", 8],
      ["celery", 2, "diced"],
      ["grapes", 1, "halved"],
      ["salt", 0.5],
      ["pepper", 0.25],
      ["bread", 14],
    ],
    steps: ["Mix the chicken, mayo, celery, grapes, salt and pepper.", "Spread thickly between bread."],
  },

  /* --- Dinner ---------------------------------------------------------- */
  {
    key: "spaghetti",
    name: "Spaghetti with Meat Sauce",
    mealTimes: ["dinner"],
    type: "Pasta",
    feeds: 8,
    activeMinutes: 10,
    totalMinutes: 30,
    tags: ["kid favorite", "stove top"],
    lines: [
      ["spaghetti", 2],
      ["ground-beef", 1.5],
      ["onion", 1, "diced"],
      ["garlic", 3, "minced"],
      ["pasta-sauce", 2],
      ["italian-seasoning", 1],
      ["parmesan", 6],
    ],
    steps: [
      "Brown the beef with the onion; drain. Add the garlic for a minute.",
      "Add the sauce and seasoning and simmer while the spaghetti cooks.",
      "Serve with parmesan.",
    ],
  },
  {
    key: "tacos-beef",
    name: "Tacos (beef)",
    mealTimes: ["dinner"],
    type: "Mexican",
    feeds: 7,
    activeMinutes: 20,
    totalMinutes: 20,
    tags: ["kid favorite", "stove top"],
    lines: [
      ["ground-beef", 2],
      ["taco-seasoning", 2],
      ["taco-shells", 18],
      ["cheddar", 2],
      ["iceberg", 3],
      ["tomato", 3, "diced"],
      ["sour-cream", 1],
      ["salsa", 1],
    ],
    steps: [
      "Brown the beef; drain. Stir in the seasoning with ⅔ cup of water per packet and simmer 5 minutes.",
      "Warm the shells in the oven.",
      "Set out the toppings and let everyone build their own.",
    ],
  },
  {
    key: "tacos-chicken",
    name: "Tacos (chicken)",
    variantOf: "tacos-beef",
    mealTimes: ["dinner"],
    type: "Mexican",
    feeds: 7,
    activeMinutes: 25,
    totalMinutes: 30,
    tags: ["stove top"],
    lines: [
      ["chicken-breast", 2],
      ["taco-seasoning", 2],
      ["small-tortillas", 20],
      ["cheddar", 2],
      ["iceberg", 3],
      ["tomato", 3, "diced"],
      ["avocado", 2, "sliced"],
      ["sour-cream", 1],
      ["salsa", 1],
      ["lime", 2, "wedges"],
      ["cilantro", 1],
    ],
    steps: [
      "Simmer the chicken in the seasoning and a cup of water, covered, 15–20 minutes; shred it in the pan.",
      "Warm the tortillas.",
      "Set out the toppings and let everyone build their own.",
    ],
  },
  {
    key: "enchiladas",
    name: "Chicken Enchiladas",
    mealTimes: ["dinner"],
    type: "Mexican",
    feeds: 8,
    activeMinutes: 30,
    totalMinutes: 60,
    tags: ["freezer", "make ahead", "oven"],
    lines: [
      ["chicken-breast", 2, "cooked and shredded"],
      ["onion", 1, "diced"],
      ["green-chiles", 1],
      ["cumin", 1],
      ["sour-cream", 1],
      ["cheddar", 3],
      ["small-tortillas", 14],
      ["enchilada-sauce", 3],
    ],
    steps: [
      "Heat the oven to 350°F. Mix the chicken, onion, chiles, cumin, sour cream and half the cheese.",
      "Spread a can of sauce in a 9×13. Fill and roll the tortillas and lay them seam down.",
      "Pour over the rest of the sauce and cheese.",
      "Bake 25–30 minutes. Freezes well before baking.",
    ],
  },
  {
    key: "homemade-pizza",
    name: "Homemade Pizza",
    mealTimes: ["dinner"],
    type: "Pizza",
    feeds: 8,
    activeMinutes: 45,
    totalMinutes: 90,
    tags: ["kid project", "oven"],
    lines: [
      ["flour", 6],
      ["yeast", 2],
      ["sugar", 0.125],
      ["salt", 2],
      ["olive-oil", 3],
      ["pizza-sauce", 1.5],
      ["mozzarella", 4],
      ["pepperoni", 6],
    ],
    steps: [
      "Stir the yeast and sugar into 2¼ cups of warm water; wait 5 minutes.",
      "Add the oil, salt and flour and knead 5 minutes. Let it rise 45 minutes.",
      "Heat the oven to 450°F. Divide into three, stretch onto greased pans.",
      "Top with sauce, cheese and pepperoni; bake 12–15 minutes.",
    ],
  },
  {
    key: "pizza-little-caesars",
    name: "Pizza Night (Little Caesars)",
    mealTimes: ["dinner"],
    type: "Pizza",
    feeds: 8,
    activeMinutes: 5,
    totalMinutes: 15,
    tags: ["kid favorite"],
    lines: [["little-caesars", 3]],
    steps: ["Three large pepperoni. Somebody picks them up on the way home."],
  },
  {
    key: "pizza-dominos",
    name: "Pizza Night (Domino's)",
    variantOf: "pizza-little-caesars",
    mealTimes: ["dinner"],
    type: "Pizza",
    feeds: 8,
    activeMinutes: 5,
    totalMinutes: 30,
    tags: ["kid favorite"],
    lines: [["dominos", 3]],
    steps: ["Three large pepperoni, carryout — the online deal is almost always cheaper than delivery."],
  },
  {
    key: "pizza-papa-murphys",
    name: "Pizza Night (Papa Murphy's)",
    variantOf: "pizza-little-caesars",
    mealTimes: ["dinner"],
    type: "Pizza",
    feeds: 8,
    activeMinutes: 5,
    totalMinutes: 30,
    tags: ["oven"],
    lines: [["papa-murphys", 3]],
    steps: ["Bake at 425°F for 12–18 minutes, on the tray they come on."],
  },
  {
    key: "pizza-frozen",
    name: "Pizza Night (frozen)",
    variantOf: "pizza-little-caesars",
    mealTimes: ["dinner"],
    type: "Pizza",
    feeds: 7,
    activeMinutes: 5,
    totalMinutes: 25,
    tags: ["oven"],
    lines: [["frozen-pizza", 4]],
    steps: ["Bake as the box says, two at a time."],
  },
  {
    key: "sloppy-joes",
    name: "Sloppy Joes",
    mealTimes: ["dinner"],
    type: "Sandwich",
    feeds: 8,
    activeMinutes: 10,
    totalMinutes: 25,
    tags: ["kid favorite", "stove top"],
    lines: [
      ["ground-beef", 2],
      ["onion", 1, "diced"],
      ["ketchup", 12],
      ["tomato-sauce", 1],
      ["brown-sugar", 0.125],
      ["mustard", 1],
      ["chili-powder", 1],
      ["hamburger-buns", 16],
    ],
    steps: [
      "Brown the beef with the onion; drain.",
      "Stir in the ketchup, tomato sauce, brown sugar, mustard and chili powder; simmer 10 minutes.",
      "Spoon onto buns.",
    ],
  },
  {
    key: "sloppy-joes-can",
    name: "Sloppy Joes (canned sauce)",
    variantOf: "sloppy-joes",
    mealTimes: ["dinner"],
    type: "Sandwich",
    feeds: 8,
    activeMinutes: 10,
    totalMinutes: 15,
    tags: ["kid favorite", "stove top"],
    lines: [
      ["ground-beef", 2],
      ["sloppy-joe-sauce", 2],
      ["hamburger-buns", 16],
    ],
    steps: ["Brown the beef and drain; stir in the sauce and heat through. Spoon onto buns."],
  },
  {
    key: "hamburgers",
    name: "Hamburgers",
    mealTimes: ["dinner"],
    type: "Meat",
    feeds: 8,
    activeMinutes: 15,
    totalMinutes: 30,
    tags: ["grill"],
    lines: [
      ["ground-beef", 3],
      ["salt", 2],
      ["pepper", 1],
      ["hamburger-buns", 12],
      ["american-cheese", 12],
      ["iceberg", 3],
      ["tomato", 3, "sliced"],
      ["onion", 1, "sliced"],
      ["ketchup", 6],
      ["mustard", 3],
      ["mayo", 4],
    ],
    steps: [
      "Shape twelve quarter-pound patties with a dimple in the middle; season both sides.",
      "Grill over medium-high heat, 4 minutes a side, adding cheese for the last minute.",
      "Toast the buns and set out the toppings.",
    ],
  },
  {
    key: "chili",
    name: "Chili",
    mealTimes: ["dinner"],
    type: "Soup",
    feeds: 10,
    activeMinutes: 20,
    totalMinutes: 60,
    tags: ["crock pot", "freezer", "make ahead", "stove top"],
    lines: [
      ["ground-beef", 2],
      ["onion", 1, "diced"],
      ["garlic", 3, "minced"],
      ["kidney-beans", 2, "drained"],
      ["pinto-beans", 2, "drained"],
      ["diced-tomatoes", 2],
      ["tomato-sauce", 2],
      ["chili-powder", 3],
      ["cumin", 2],
      ["salt", 1],
      ["cheddar", 1, "for the top"],
      ["sour-cream", 0.5, "for the top"],
    ],
    steps: [
      "Brown the beef with the onion; drain. Add the garlic for a minute.",
      "Stir in everything else except the cheese and sour cream.",
      "Simmer 30 minutes (or 6 hours on low in the crock pot).",
      "Top with cheese and sour cream.",
    ],
  },
  {
    key: "pulled-pork",
    name: "Crock Pot Pulled Pork Sandwiches",
    mealTimes: ["dinner"],
    type: "Crock Pot",
    feeds: 12,
    activeMinutes: 15,
    totalMinutes: 480,
    tags: ["crock pot", "make ahead", "freezer"],
    lines: [
      ["pork-shoulder", 4],
      ["onion", 1, "sliced"],
      ["brown-sugar", 0.25],
      ["salt", 2],
      ["bbq-sauce", 1.75],
      ["hamburger-buns", 16],
    ],
    steps: [
      "Rub the pork with the brown sugar and salt; set it on the onion in the crock pot.",
      "Cook on low for 8 hours, until it falls apart.",
      "Pour off most of the liquid, shred the meat, and stir in the BBQ sauce.",
      "Pile onto buns.",
    ],
  },
  {
    key: "alfredo",
    name: "Chicken Alfredo",
    mealTimes: ["dinner"],
    type: "Pasta",
    feeds: 8,
    activeMinutes: 25,
    totalMinutes: 35,
    tags: ["stove top"],
    lines: [
      ["fettuccine", 1.5],
      ["chicken-breast", 2, "sliced"],
      ["butter", 8],
      ["garlic", 3, "minced"],
      ["heavy-cream", 2],
      ["parmesan", 16],
      ["broccoli", 3],
      ["salt", 1],
      ["pepper", 0.5],
    ],
    steps: [
      "Cook the fettuccine, adding the broccoli for the last 3 minutes; drain.",
      "Brown the chicken in a little of the butter; set aside.",
      "Melt the rest of the butter with the garlic, add the cream and simmer 5 minutes, then stir in the parmesan.",
      "Toss everything together; season.",
    ],
  },
  {
    key: "teriyaki-chicken",
    name: "Teriyaki Chicken & Rice",
    mealTimes: ["dinner"],
    type: "Ethnic",
    feeds: 8,
    activeMinutes: 20,
    totalMinutes: 40,
    tags: ["stove top"],
    lines: [
      ["rice", 3],
      ["chicken-thighs", 2.5, "cut into bites"],
      ["vegetable-oil", 2],
      ["teriyaki", 1],
      ["stir-fry-veg", 4],
      ["green-onions", 1, "sliced"],
    ],
    steps: [
      "Cook the rice.",
      "Brown the chicken in the oil in a big skillet, in batches.",
      "Add the vegetables for 5 minutes, then the sauce; simmer until glossy.",
      "Serve over rice with green onions.",
    ],
  },
  {
    key: "fried-rice",
    name: "Chicken Fried Rice",
    mealTimes: ["dinner"],
    type: "Ethnic",
    feeds: 8,
    activeMinutes: 25,
    totalMinutes: 30,
    tags: ["stove top"],
    lines: [
      ["rice", 3, "cooked a day ahead if you can"],
      ["chicken-breast", 1.5, "diced"],
      ["vegetable-oil", 3],
      ["eggs", 4],
      ["frozen-peas", 1],
      ["carrots", 1, "diced"],
      ["garlic", 2, "minced"],
      ["green-onions", 1],
      ["soy-sauce", 5],
    ],
    steps: [
      "Cook the chicken in a tablespoon of oil; set aside.",
      "Scramble the eggs; set aside.",
      "Fry the carrots, peas and garlic in the rest of the oil, then the cold rice, until hot.",
      "Stir back in the chicken and egg with the soy sauce and green onions.",
    ],
  },
  {
    key: "shepherds-pie",
    name: "Shepherd's Pie",
    mealTimes: ["dinner"],
    type: "Entree",
    feeds: 8,
    activeMinutes: 35,
    totalMinutes: 60,
    tags: ["oven", "freezer"],
    lines: [
      ["potatoes", 3],
      ["butter", 6],
      ["milk", 0.75],
      ["ground-beef", 2],
      ["onion", 1, "diced"],
      ["gravy-mix", 2],
      ["mixed-veg", 3],
      ["cheddar", 1],
      ["salt", 1],
    ],
    steps: [
      "Boil the potatoes and mash with the butter, milk and salt.",
      "Brown the beef with the onion; drain. Stir in the gravy mix with 2 cups of water and the vegetables.",
      "Spread in a 9×13, top with the potatoes and cheese.",
      "Bake at 400°F for 20 minutes.",
    ],
  },
  {
    key: "lasagna",
    name: "Lasagna",
    mealTimes: ["dinner"],
    type: "Pasta",
    feeds: 12,
    activeMinutes: 40,
    totalMinutes: 100,
    tags: ["freezer", "holiday", "make ahead", "oven"],
    lines: [
      ["lasagna-noodles", 1],
      ["ground-beef", 1.5],
      ["pasta-sauce", 2],
      ["ricotta", 1.75],
      ["eggs", 1],
      ["mozzarella", 4],
      ["parmesan", 8],
      ["italian-seasoning", 2],
    ],
    steps: [
      "Cook the noodles. Brown and drain the beef, then add the sauce.",
      "Mix the ricotta, egg, half the parmesan and the seasoning.",
      "Layer in a 9×13: sauce, noodles, ricotta, mozzarella — three times, sauce and cheese on top.",
      "Cover with foil and bake at 375°F for 45 minutes; uncover for 15. Rest 10 before cutting.",
    ],
  },
  {
    key: "baked-potato-bar",
    name: "Baked Potato Bar",
    mealTimes: ["dinner"],
    type: "Entree",
    feeds: 7,
    activeMinutes: 15,
    totalMinutes: 75,
    tags: ["oven", "kid favorite"],
    lines: [
      ["potatoes", 5],
      ["butter", 7],
      ["sour-cream", 1],
      ["cheddar", 2],
      ["bacon", 8, "cooked and crumbled"],
      ["green-onions", 1],
      ["broccoli", 3, "steamed"],
    ],
    steps: [
      "Scrub the potatoes, poke them with a fork and bake at 400°F for an hour.",
      "Cook the bacon and steam the broccoli while they bake.",
      "Split the potatoes and set out the toppings.",
    ],
  },
  {
    key: "sheet-pan-sausage",
    name: "Sheet Pan Sausage & Veggies",
    mealTimes: ["dinner"],
    type: "Meat",
    feeds: 7,
    activeMinutes: 20,
    totalMinutes: 45,
    tags: ["oven"],
    lines: [
      ["smoked-sausage", 2, "sliced"],
      ["potatoes", 3, "cubed"],
      ["bell-pepper", 2, "chopped"],
      ["zucchini", 2, "chopped"],
      ["onion", 1, "chopped"],
      ["olive-oil", 3],
      ["italian-seasoning", 2],
      ["garlic-powder", 1],
      ["salt", 1],
    ],
    steps: [
      "Heat the oven to 425°F.",
      "Toss the potatoes with half the oil and seasoning; roast 15 minutes.",
      "Add everything else, tossed in the rest; roast 20 more minutes.",
    ],
  },
  {
    key: "haystacks",
    name: "Hawaiian Haystacks",
    mealTimes: ["dinner"],
    type: "Entree",
    feeds: 8,
    activeMinutes: 25,
    totalMinutes: 45,
    tags: ["kid favorite", "stove top"],
    lines: [
      ["rice", 3],
      ["chicken-breast", 2, "cooked and diced"],
      ["cream-of-chicken", 2],
      ["chicken-broth", 1],
      ["sour-cream", 1],
      ["cheddar", 1.5],
      ["pineapple", 1],
      ["mandarins", 1],
      ["tomato", 3, "diced"],
      ["green-onions", 1],
    ],
    steps: [
      "Cook the rice.",
      "Simmer the chicken, soup and broth together; stir in the sour cream off the heat.",
      "Rice, then gravy, then pile on the toppings.",
    ],
  },
  {
    key: "ranch-chicken",
    name: "Crock Pot Ranch Chicken",
    mealTimes: ["dinner"],
    type: "Crock Pot",
    feeds: 8,
    activeMinutes: 10,
    totalMinutes: 250,
    tags: ["crock pot"],
    lines: [
      ["chicken-breast", 3],
      ["cream-cheese", 8],
      ["ranch-mix", 1],
      ["cream-of-chicken", 1],
      ["rice", 3],
    ],
    steps: [
      "Put the chicken in the crock pot; top with the soup, ranch mix and the cream cheese in cubes.",
      "Cook on low 4 hours. Shred the chicken and stir it all together.",
      "Serve over rice.",
    ],
  },
  {
    key: "pot-roast",
    name: "Pot Roast",
    mealTimes: ["dinner"],
    type: "Crock Pot",
    feeds: 8,
    activeMinutes: 20,
    totalMinutes: 480,
    tags: ["crock pot", "holiday"],
    lines: [
      ["chuck-roast", 3],
      ["potatoes", 3, "in chunks"],
      ["carrots", 4, "in chunks"],
      ["onion", 2, "quartered"],
      ["garlic", 3],
      ["beef-broth", 2],
      ["gravy-mix", 2],
      ["salt", 1],
      ["pepper", 1],
    ],
    steps: [
      "Season the roast and brown it on every side in a hot pan.",
      "Put the vegetables in the crock pot, the roast on top.",
      "Whisk the gravy mix into the broth and pour over. Cook on low 8 hours.",
    ],
  },
  {
    key: "meatloaf",
    name: "Meatloaf & Mashed Potatoes",
    mealTimes: ["dinner"],
    type: "Meat",
    feeds: 8,
    activeMinutes: 30,
    totalMinutes: 80,
    tags: ["oven"],
    lines: [
      ["ground-beef", 2],
      ["eggs", 2],
      ["oats", 0.75],
      ["milk", 1.5, "half for the loaf, half for the potatoes"],
      ["onion", 1, "diced fine"],
      ["ketchup", 10],
      ["brown-sugar", 0.25],
      ["mustard", 1],
      ["salt", 3],
      ["potatoes", 4],
      ["butter", 6],
    ],
    steps: [
      "Heat the oven to 350°F. Mix the beef, eggs, oats, half the milk, the onion, 4 tbsp ketchup and 1½ tsp salt.",
      "Shape into a loaf on a lined pan. Mix the rest of the ketchup with the brown sugar and mustard and spread over.",
      "Bake an hour.",
      "Meanwhile boil the potatoes and mash with the butter, the rest of the milk and salt.",
    ],
  },
  {
    key: "bbq-drumsticks",
    name: "BBQ Chicken Drumsticks",
    mealTimes: ["dinner"],
    type: "Meat",
    feeds: 8,
    activeMinutes: 10,
    totalMinutes: 60,
    tags: ["grill", "oven"],
    lines: [
      ["drumsticks", 5],
      ["salt", 2],
      ["garlic-powder", 1],
      ["bbq-sauce", 1.5],
    ],
    steps: [
      "Season the drumsticks with the salt and garlic powder.",
      "Bake at 400°F for 40 minutes (or grill over medium heat, turning).",
      "Brush with BBQ sauce and cook 10 more minutes.",
    ],
  },
  {
    key: "fish-sticks",
    name: "Fish Sticks & Fries",
    mealTimes: ["dinner"],
    type: "Kid",
    feeds: 7,
    activeMinutes: 5,
    totalMinutes: 25,
    tags: ["kid favorite", "oven", "air fryer"],
    lines: [
      ["fish-sticks", 30],
      ["fries", 7],
      ["ketchup", 8],
    ],
    steps: ["Bake the fries and fish sticks together at 425°F, about 20 minutes, turning once."],
  },
  {
    key: "nuggets",
    name: "Chicken Nuggets & Fries",
    mealTimes: ["dinner", "lunch"],
    type: "Kid",
    feeds: 7,
    activeMinutes: 5,
    totalMinutes: 25,
    tags: ["kid favorite", "oven", "air fryer"],
    lines: [
      ["nuggets", 42],
      ["fries", 7],
      ["ketchup", 8],
      ["ranch", 8],
    ],
    steps: ["Bake the nuggets and fries at 425°F, about 20 minutes, turning once. Ketchup and ranch for dipping."],
  },
  {
    key: "stroganoff",
    name: "Beef Stroganoff",
    mealTimes: ["dinner"],
    type: "Pasta",
    feeds: 8,
    activeMinutes: 20,
    totalMinutes: 30,
    tags: ["stove top"],
    lines: [
      ["ground-beef", 2],
      ["onion", 1, "diced"],
      ["mushrooms", 3],
      ["cream-of-mushroom", 2],
      ["beef-broth", 1],
      ["sour-cream", 1],
      ["egg-noodles", 24],
    ],
    steps: [
      "Cook the noodles.",
      "Brown the beef with the onion and mushrooms; drain.",
      "Stir in the soup and broth and simmer 5 minutes; stir in the sour cream off the heat.",
      "Serve over the noodles.",
    ],
  },
  {
    key: "tuna-casserole",
    name: "Tuna Noodle Casserole",
    mealTimes: ["dinner"],
    type: "Entree",
    feeds: 8,
    activeMinutes: 15,
    totalMinutes: 40,
    tags: ["oven"],
    lines: [
      ["egg-noodles", 12],
      ["tuna", 3, "drained"],
      ["cream-of-mushroom", 2],
      ["milk", 1],
      ["frozen-peas", 1.5],
      ["cheddar", 1.5],
    ],
    steps: [
      "Cook the noodles a minute short; drain.",
      "Mix with the tuna, soup, milk, peas and half the cheese; spread in a 9×13.",
      "Top with the rest of the cheese and bake at 375°F for 20 minutes.",
    ],
  },
  {
    key: "chicken-pot-pie",
    name: "Chicken Pot Pie",
    mealTimes: ["dinner"],
    type: "Entree",
    feeds: 8,
    activeMinutes: 20,
    totalMinutes: 60,
    tags: ["oven", "freezer"],
    lines: [
      ["chicken-breast", 1.5, "cooked and diced"],
      ["mixed-veg", 3],
      ["cream-of-chicken", 2],
      ["milk", 0.5],
      ["pepper", 0.5],
      ["pie-crust", 2],
    ],
    steps: [
      "Heat the oven to 400°F. Line a deep pie dish with one crust.",
      "Mix the chicken, vegetables, soup, milk and pepper; pour in.",
      "Top with the second crust, crimp, and cut vents.",
      "Bake 35–40 minutes, until golden.",
    ],
  },
  {
    key: "chicken-pot-pie-biscuit",
    name: "Chicken Pot Pie (biscuit top)",
    variantOf: "chicken-pot-pie",
    mealTimes: ["dinner"],
    type: "Entree",
    feeds: 8,
    activeMinutes: 15,
    totalMinutes: 40,
    tags: ["oven"],
    lines: [
      ["chicken-breast", 1.5, "cooked and diced"],
      ["mixed-veg", 3],
      ["cream-of-chicken", 2],
      ["milk", 0.5],
      ["pepper", 0.5],
      ["biscuits", 1],
    ],
    steps: [
      "Heat the filling in a 9×13 at 400°F for 10 minutes.",
      "Lay the biscuits on top and bake 15–18 minutes, until they are golden.",
    ],
  },
  {
    key: "taco-soup",
    name: "Taco Soup",
    mealTimes: ["dinner"],
    type: "Soup",
    feeds: 10,
    activeMinutes: 15,
    totalMinutes: 40,
    tags: ["crock pot", "freezer", "stove top"],
    lines: [
      ["ground-beef", 2],
      ["onion", 1, "diced"],
      ["black-beans", 2],
      ["pinto-beans", 1],
      ["frozen-corn", 2],
      ["diced-tomatoes", 2],
      ["tomato-sauce", 1],
      ["taco-seasoning", 2],
      ["ranch-mix", 1],
      ["tortilla-chips", 8],
      ["cheddar", 1],
      ["sour-cream", 0.5],
    ],
    steps: [
      "Brown the beef with the onion; drain.",
      "Add the beans, corn and tomatoes with their liquid, the sauce and both seasonings.",
      "Simmer 20 minutes.",
      "Serve with chips, cheese and sour cream.",
    ],
  },
  {
    key: "broccoli-cheese-soup",
    name: "Broccoli Cheese Soup",
    mealTimes: ["dinner", "lunch"],
    type: "Soup",
    feeds: 7,
    activeMinutes: 20,
    totalMinutes: 40,
    tags: ["stove top"],
    lines: [
      ["butter", 4],
      ["onion", 1, "diced"],
      ["flour", 0.33],
      ["chicken-broth", 4],
      ["milk", 2],
      ["broccoli", 6, "chopped"],
      ["carrots", 1, "grated"],
      ["cheddar", 3],
      ["french-bread", 1, "to go with"],
    ],
    steps: [
      "Soften the onion in the butter; stir in the flour for a minute.",
      "Whisk in the broth and milk; add the broccoli and carrots and simmer 20 minutes.",
      "Stir in the cheese a handful at a time until melted.",
      "Serve with bread.",
    ],
  },
  {
    key: "white-chicken-chili",
    name: "White Chicken Chili",
    mealTimes: ["dinner"],
    type: "Soup",
    feeds: 10,
    activeMinutes: 15,
    totalMinutes: 250,
    tags: ["crock pot", "freezer"],
    lines: [
      ["chicken-breast", 2],
      ["white-beans", 3],
      ["chicken-broth", 3],
      ["green-chiles", 2],
      ["frozen-corn", 2],
      ["onion", 1, "diced"],
      ["garlic", 3, "minced"],
      ["cumin", 2],
      ["salt", 1],
      ["cream-cheese", 8],
    ],
    steps: [
      "Put everything but the cream cheese in the crock pot.",
      "Cook on low 4 hours. Shred the chicken.",
      "Stir in the cream cheese until melted.",
    ],
  },
  {
    key: "navajo-tacos",
    name: "Navajo Tacos",
    mealTimes: ["dinner"],
    type: "Mexican",
    feeds: 8,
    activeMinutes: 45,
    totalMinutes: 60,
    tags: ["stove top", "kid favorite"],
    lines: [
      ["flour", 4],
      ["baking-powder", 4],
      ["salt", 1],
      ["milk", 1.5],
      ["vegetable-oil", 16, "for frying"],
      ["ground-beef", 1.5],
      ["pinto-beans", 2],
      ["taco-seasoning", 1],
      ["cheddar", 2],
      ["iceberg", 3],
      ["tomato", 3, "diced"],
      ["sour-cream", 1],
      ["salsa", 1],
    ],
    steps: [
      "Mix the flour, baking powder, salt and milk into a soft dough; rest 15 minutes.",
      "Brown the beef, add the beans and seasoning with a little water, and simmer.",
      "Stretch the dough into eight rounds and fry in hot oil until puffed and golden on both sides.",
      "Top the fry bread with the chili and everything else.",
    ],
  },
  {
    key: "salmon",
    name: "Lemon Garlic Salmon",
    mealTimes: ["dinner"],
    type: "Meat",
    feeds: 7,
    activeMinutes: 10,
    totalMinutes: 25,
    tags: ["oven"],
    lines: [
      ["salmon", 3],
      ["butter", 4, "melted"],
      ["garlic", 4, "minced"],
      ["lemon", 2],
      ["salt", 1],
      ["pepper", 0.5],
    ],
    steps: [
      "Heat the oven to 400°F. Lay the salmon on a lined pan.",
      "Mix the butter, garlic, the juice of one lemon, salt and pepper; spoon over.",
      "Bake 12–15 minutes. Serve with the other lemon in wedges.",
    ],
  },
  {
    key: "chicken-salad",
    name: "Grilled Chicken Salad",
    mealTimes: ["dinner", "lunch"],
    type: "Salad",
    feeds: 7,
    activeMinutes: 25,
    totalMinutes: 35,
    tags: ["grill"],
    lines: [
      ["chicken-breast", 2],
      ["olive-oil", 1],
      ["garlic-powder", 1],
      ["salt", 1],
      ["romaine", 14],
      ["tomato", 4],
      ["cucumber", 2],
      ["cheddar", 1],
      ["ranch", 14],
    ],
    steps: [
      "Rub the chicken with the oil, garlic powder and salt; grill until 165°F inside. Rest, then slice.",
      "Chop the lettuce, tomatoes and cucumber.",
      "Top with the chicken and cheese; dressing on the side.",
    ],
  },
  {
    key: "sweet-sour-meatballs",
    name: "Sweet & Sour Meatballs",
    mealTimes: ["dinner"],
    type: "Crock Pot",
    feeds: 8,
    activeMinutes: 15,
    totalMinutes: 180,
    tags: ["crock pot"],
    lines: [
      ["meatballs", 50],
      ["pineapple", 1, "juice and all"],
      ["bell-pepper", 2, "chunks"],
      ["brown-sugar", 0.5],
      ["ketchup", 6],
      ["soy-sauce", 3],
      ["cornstarch", 2],
      ["rice", 3],
    ],
    steps: [
      "Whisk the pineapple juice, brown sugar, ketchup, soy sauce and cornstarch.",
      "Put the meatballs, pineapple and pepper in the crock pot and pour the sauce over.",
      "Cook on low 3 hours. Serve over rice.",
    ],
  },

  /* --- Sides ----------------------------------------------------------- */
  {
    key: "garlic-bread",
    name: "Garlic Bread",
    mealTimes: ["side"],
    type: "Bread",
    feeds: 8,
    activeMinutes: 5,
    totalMinutes: 15,
    tags: ["oven"],
    lines: [
      ["french-bread", 1],
      ["butter", 8, "softened"],
      ["garlic-powder", 1],
      ["parmesan", 3],
    ],
    steps: [
      "Split the loaf lengthwise. Mix the butter, garlic powder and parmesan and spread it on.",
      "Bake at 400°F for 8–10 minutes.",
    ],
  },
  {
    key: "green-salad",
    name: "Green Salad",
    mealTimes: ["side"],
    type: "Salad",
    feeds: 8,
    activeMinutes: 10,
    totalMinutes: 10,
    tags: ["no bake"],
    lines: [
      ["romaine", 10],
      ["tomato", 3],
      ["cucumber", 1],
      ["carrots", 1, "grated"],
      ["ranch", 10],
    ],
    steps: ["Chop and toss; dressing on the side."],
  },
  {
    key: "roasted-broccoli",
    name: "Roasted Broccoli",
    mealTimes: ["side"],
    type: "Vegetable",
    feeds: 7,
    activeMinutes: 5,
    totalMinutes: 25,
    tags: ["oven"],
    lines: [
      ["broccoli", 8],
      ["olive-oil", 3],
      ["garlic-powder", 1],
      ["salt", 1],
      ["parmesan", 4],
    ],
    steps: [
      "Toss the broccoli with the oil, garlic powder and salt.",
      "Roast at 425°F for 20 minutes; sprinkle with parmesan.",
    ],
  },
  {
    key: "mashed-potatoes",
    name: "Mashed Potatoes",
    mealTimes: ["side"],
    type: "Side",
    feeds: 10,
    activeMinutes: 15,
    totalMinutes: 40,
    tags: ["stove top", "holiday"],
    lines: [
      ["potatoes", 5],
      ["butter", 8],
      ["milk", 1.25],
      ["salt", 2],
      ["pepper", 0.5],
    ],
    steps: [
      "Peel and chunk the potatoes; boil until tender, about 20 minutes. Drain.",
      "Mash with the butter, warm milk, salt and pepper.",
    ],
  },
  {
    key: "buttered-corn",
    name: "Buttered Corn",
    mealTimes: ["side"],
    type: "Vegetable",
    feeds: 7,
    activeMinutes: 2,
    totalMinutes: 8,
    tags: ["microwave", "stove top"],
    lines: [
      ["frozen-corn", 5],
      ["butter", 3],
      ["salt", 0.5],
    ],
    steps: ["Heat the corn; stir in the butter and salt."],
  },
  {
    key: "white-rice",
    name: "White Rice",
    mealTimes: ["side"],
    type: "Side",
    feeds: 9,
    activeMinutes: 2,
    totalMinutes: 25,
    tags: ["stove top"],
    lines: [
      ["rice", 3],
      ["butter", 2],
      ["salt", 1],
    ],
    steps: [
      "Bring 6 cups of water, the butter and salt to a boil. Stir in the rice.",
      "Cover, turn to low and cook 18 minutes. Rest 5, then fluff.",
    ],
  },
  {
    key: "fruit-salad",
    name: "Fruit Salad",
    mealTimes: ["side", "dessert"],
    type: "Fruit",
    feeds: 10,
    activeMinutes: 15,
    totalMinutes: 15,
    tags: ["no bake", "kid project"],
    lines: [
      ["strawberries", 3],
      ["grapes", 3],
      ["banana", 3],
      ["apple", 2],
      ["mandarins", 1, "drained"],
      ["pineapple", 1, "drained"],
    ],
    steps: ["Cut everything bite-sized and fold together. Add the bananas last so they don't brown."],
  },
  {
    key: "funeral-potatoes",
    name: "Funeral Potatoes",
    mealTimes: ["side"],
    type: "Side",
    feeds: 12,
    activeMinutes: 15,
    totalMinutes: 60,
    tags: ["holiday", "oven", "make ahead"],
    lines: [
      ["hash-browns", 8, "thawed"],
      ["cream-of-chicken", 1],
      ["sour-cream", 2],
      ["cheddar", 2],
      ["butter", 8, "melted"],
      ["onion", 0.5, "diced fine"],
      ["cereal", 2, "crushed, for the top"],
    ],
    steps: [
      "Mix the potatoes, soup, sour cream, cheese, half the butter and the onion; spread in a 9×13.",
      "Toss the crushed cereal with the rest of the butter and sprinkle over.",
      "Bake at 350°F for 45 minutes.",
    ],
  },
  {
    key: "green-beans",
    name: "Green Beans with Bacon",
    mealTimes: ["side"],
    type: "Vegetable",
    feeds: 8,
    activeMinutes: 5,
    totalMinutes: 20,
    tags: ["stove top"],
    lines: [
      ["green-beans", 6],
      ["bacon", 4, "chopped"],
      ["onion", 0.5, "diced"],
      ["butter", 2],
      ["salt", 0.5],
    ],
    steps: ["Crisp the bacon; soften the onion in the fat.", "Add the beans and butter and cook until hot; season."],
  },
  {
    key: "dinner-rolls",
    name: "Dinner Rolls",
    mealTimes: ["side"],
    type: "Bread",
    feeds: 24,
    activeMinutes: 30,
    totalMinutes: 150,
    tags: ["holiday", "oven", "kid project"],
    lines: [
      ["milk", 2, "warm"],
      ["yeast", 2],
      ["sugar", 0.5],
      ["butter", 8, "melted"],
      ["eggs", 2],
      ["salt", 2],
      ["flour", 6],
    ],
    steps: [
      "Stir the yeast and sugar into the warm milk; wait 5 minutes.",
      "Add the butter, eggs, salt and flour and knead until smooth. Rise an hour.",
      "Shape into 24 rolls in a greased 9×13; rise 30 minutes.",
      "Bake at 375°F for 15–18 minutes; brush with butter.",
    ],
  },

  /* --- Desserts -------------------------------------------------------- */
  {
    key: "chocolate-chip-cookies",
    name: "Chocolate Chip Cookies",
    mealTimes: ["dessert"],
    type: "Dessert",
    feeds: 18,
    activeMinutes: 20,
    totalMinutes: 35,
    tags: ["treat", "kid project", "oven"],
    lines: [
      ["butter", 16, "softened"],
      ["sugar", 0.75],
      ["brown-sugar", 0.75],
      ["eggs", 2],
      ["vanilla", 2],
      ["flour", 2.25],
      ["baking-soda", 1],
      ["salt", 1],
      ["chocolate-chips", 2],
    ],
    steps: [
      "Heat the oven to 375°F. Cream the butter and sugars; beat in the eggs and vanilla.",
      "Stir in the flour, baking soda and salt, then the chips.",
      "Drop by rounded tablespoons; bake 9–11 minutes. Makes about 36.",
    ],
  },
  {
    key: "brownies-box",
    name: "Brownies (box)",
    mealTimes: ["dessert"],
    type: "Dessert",
    feeds: 16,
    activeMinutes: 5,
    totalMinutes: 35,
    tags: ["treat", "oven"],
    lines: [
      ["brownie-mix", 1],
      ["eggs", 2],
      ["vegetable-oil", 8],
    ],
    steps: ["Mix with the eggs, oil and ¼ cup of water; bake as the box says."],
  },
  {
    key: "brownies-scratch",
    name: "Brownies (from scratch)",
    variantOf: "brownies-box",
    mealTimes: ["dessert"],
    type: "Dessert",
    feeds: 16,
    activeMinutes: 15,
    totalMinutes: 45,
    tags: ["treat", "oven"],
    lines: [
      ["butter", 16, "melted"],
      ["sugar", 2],
      ["eggs", 4],
      ["vanilla", 1],
      ["cocoa", 12],
      ["flour", 1],
      ["salt", 0.5],
      ["baking-powder", 0.5],
    ],
    steps: [
      "Heat the oven to 350°F. Stir the butter and sugar, then the eggs and vanilla.",
      "Stir in the cocoa, flour, salt and baking powder.",
      "Spread in a greased 9×13 and bake 25–30 minutes.",
    ],
  },
  {
    key: "rice-krispie-treats",
    name: "Crispy Rice Treats",
    mealTimes: ["dessert", "other"],
    type: "Dessert",
    feeds: 12,
    activeMinutes: 10,
    totalMinutes: 40,
    tags: ["treat", "no bake", "kid project"],
    lines: [
      ["butter", 3],
      ["marshmallows", 6],
      ["crisp-rice", 6],
    ],
    steps: [
      "Melt the butter and marshmallows over low heat.",
      "Stir in the cereal and press into a buttered 9×13. Cool before cutting.",
    ],
  },
  {
    key: "banana-bread",
    name: "Banana Bread",
    mealTimes: ["dessert", "breakfast"],
    type: "Baking",
    feeds: 10,
    activeMinutes: 15,
    totalMinutes: 75,
    tags: ["oven", "freezer"],
    lines: [
      ["banana", 3, "very ripe"],
      ["butter", 6, "melted"],
      ["sugar", 0.75],
      ["eggs", 1],
      ["vanilla", 1],
      ["baking-soda", 1],
      ["salt", 0.25],
      ["flour", 1.5],
    ],
    steps: [
      "Heat the oven to 350°F. Mash the bananas; stir in the butter, sugar, egg and vanilla.",
      "Stir in the soda, salt and flour.",
      "Bake in a greased loaf pan for 55–60 minutes.",
    ],
  },
  {
    key: "apple-crisp",
    name: "Apple Crisp",
    mealTimes: ["dessert"],
    type: "Dessert",
    feeds: 8,
    activeMinutes: 20,
    totalMinutes: 60,
    tags: ["oven", "holiday"],
    lines: [
      ["apple", 6, "sliced"],
      ["sugar", 0.5],
      ["cinnamon", 2],
      ["oats", 1],
      ["flour", 0.75],
      ["brown-sugar", 0.75],
      ["butter", 8, "cold"],
      ["ice-cream", 3],
    ],
    steps: [
      "Heat the oven to 350°F. Toss the apples with the sugar and cinnamon in a 9×13.",
      "Rub the oats, flour, brown sugar and butter together and scatter over.",
      "Bake 40 minutes. Serve warm with ice cream.",
    ],
  },
  {
    key: "no-bake-cookies",
    name: "No-Bake Cookies",
    mealTimes: ["dessert"],
    type: "Dessert",
    feeds: 12,
    activeMinutes: 15,
    totalMinutes: 45,
    tags: ["treat", "no bake"],
    lines: [
      ["sugar", 2],
      ["butter", 8],
      ["milk", 0.5],
      ["cocoa", 4],
      ["peanut-butter", 8],
      ["vanilla", 1],
      ["oats", 3],
    ],
    steps: [
      "Bring the sugar, butter, milk and cocoa to a rolling boil for 1 minute.",
      "Off the heat, stir in the peanut butter, vanilla and oats.",
      "Drop onto wax paper and let set. Makes about 24.",
    ],
  },
  {
    key: "sundaes",
    name: "Ice Cream Sundaes",
    mealTimes: ["dessert"],
    type: "Dessert",
    feeds: 7,
    activeMinutes: 5,
    totalMinutes: 5,
    tags: ["treat", "no bake", "kid favorite"],
    lines: [
      ["ice-cream", 6],
      ["chocolate-syrup", 7],
      ["whipped-topping", 1],
      ["banana", 2, "sliced"],
    ],
    steps: ["Scoop, drizzle, top."],
  },
  {
    key: "chocolate-cake",
    name: "Chocolate Cake",
    mealTimes: ["dessert"],
    type: "Dessert",
    feeds: 15,
    activeMinutes: 10,
    totalMinutes: 60,
    tags: ["treat", "holiday", "oven"],
    lines: [
      ["cake-mix", 1],
      ["eggs", 3],
      ["vegetable-oil", 8],
      ["frosting", 1],
    ],
    steps: ["Mix with the eggs, oil and 1 cup of water; bake in a 9×13 as the box says.", "Cool completely, then frost."],
  },

  /* --- Snacks and drinks ----------------------------------------------- */
  {
    key: "popcorn",
    name: "Stovetop Popcorn",
    mealTimes: ["other"],
    type: "Snack",
    feeds: 7,
    activeMinutes: 10,
    totalMinutes: 10,
    tags: ["stove top"],
    lines: [
      ["popcorn", 0.5],
      ["vegetable-oil", 3],
      ["butter", 4, "melted"],
      ["salt", 1],
    ],
    steps: [
      "Heat the oil with three kernels in a big covered pot. When they pop, add the rest.",
      "Shake over the heat until the popping slows to a few seconds apart.",
      "Toss with the butter and salt.",
    ],
  },
  {
    key: "ants-on-a-log",
    name: "Ants on a Log",
    mealTimes: ["other"],
    type: "Snack",
    feeds: 7,
    activeMinutes: 10,
    totalMinutes: 10,
    tags: ["no bake", "kid project"],
    lines: [
      ["celery", 7],
      ["peanut-butter", 7],
      ["raisins", 0.25],
    ],
    steps: ["Fill each celery stalk with peanut butter and line up the raisins."],
  },
  {
    key: "salsa-and-chips",
    name: "Homemade Salsa & Chips",
    mealTimes: ["other", "side"],
    type: "Sauce",
    feeds: 8,
    activeMinutes: 15,
    totalMinutes: 15,
    tags: ["no bake"],
    lines: [
      ["tomato", 8, "diced"],
      ["onion", 0.5, "diced"],
      ["jalapeno", 2, "seeded and minced"],
      ["cilantro", 1, "chopped"],
      ["lime", 1, "juiced"],
      ["garlic", 1, "minced"],
      ["salt", 1],
      ["tortilla-chips", 13],
    ],
    steps: ["Stir everything but the chips together. Better after half an hour in the fridge."],
  },
  {
    key: "apples-peanut-butter",
    name: "Apples & Peanut Butter",
    mealTimes: ["other"],
    type: "Snack",
    feeds: 7,
    activeMinutes: 5,
    totalMinutes: 5,
    tags: ["no bake"],
    lines: [
      ["apple", 4, "sliced"],
      ["peanut-butter", 8],
    ],
    steps: ["Slice the apples; a spoonful of peanut butter each for dipping."],
  },
  {
    key: "lemonade",
    name: "Fresh Lemonade",
    mealTimes: ["other"],
    type: "Drink",
    feeds: 10,
    activeMinutes: 10,
    totalMinutes: 10,
    tags: ["no bake", "kid project"],
    lines: [
      ["lemon", 8, "juiced"],
      ["sugar", 1.5],
    ],
    steps: [
      "Dissolve the sugar in a cup of hot water.",
      "Add the lemon juice and 8 cups of cold water. Serve over ice.",
    ],
  },
  {
    key: "hot-cocoa",
    name: "Hot Cocoa",
    mealTimes: ["other"],
    type: "Drink",
    feeds: 7,
    activeMinutes: 10,
    totalMinutes: 10,
    tags: ["stove top", "holiday"],
    lines: [
      ["milk", 7],
      ["cocoa", 7],
      ["sugar", 0.5],
      ["vanilla", 1],
      ["marshmallows", 1],
    ],
    steps: [
      "Whisk the cocoa and sugar with a splash of the milk into a paste, then the rest of the milk.",
      "Heat until steaming — don't boil. Stir in the vanilla. Marshmallows on top.",
    ],
  },
];
