/**
 * Generated by `npm run music:generate` — do not edit by hand.
 *
 * The award-ceremony music, content-hashed exactly as the cheer and the
 * photographs are, so `next.config.ts` can serve it `immutable` for a year.
 *
 * See `scripts/generate-fanfare.mjs` for the score and how it is made.
 */

export const FANFARE_SOUND = "/sounds/fanfare-020b2ef43b.mp3" as const;

/**
 * Seconds. The piece is written to loop *exactly* here — every tail wraps
 * around into the start — so playback sets `loop = true` and leaves the loop
 * points alone.
 */
export const FANFARE_DURATION_SECONDS = 22.5;
