/**
 * Generated by `npm run pets:generate` — do not edit by hand.
 *
 * Maps each pet's id to its optimised photograph. The filenames carry a
 * content hash, so they change whenever the picture does and never otherwise.
 * That is what lets `next.config.ts` serve them `immutable` for a year and
 * the service worker treat them as cache-first.
 *
 * Every file is exactly `PET_PHOTO_WIDTH` x `PET_PHOTO_HEIGHT`, with the
 * animal trimmed and centred, which is what makes the avatar coordinates in
 * `src/config/pets.ts` reusable across both pets.
 *
 * Re-run the script after replacing anything in `assets/pets/`.
 */

export const PET_PHOTO_WIDTH = 828;
export const PET_PHOTO_HEIGHT = 552;

export const PET_PHOTO_SOURCES = {
  bella: "/pets/bella-59aec1e1b8.png",
  leia: "/pets/leia-b9caf2abf8.png",
} as const satisfies Record<string, `/pets/${string}`>;

export type PetPhotoId = keyof typeof PET_PHOTO_SOURCES;
