/**
 * Generated by `npm run sound:generate` — do not edit by hand.
 *
 * The celebration sound, content-hashed exactly as the avatars and pet photos
 * are, so `next.config.ts` can serve it `immutable` for a year and the
 * service worker can precache it and never revalidate.
 *
 * See `scripts/generate-cheer.mjs` for how it is made and how to replace it
 * with a recording of the real children.
 */

export const CHEER_SOUND = "/sounds/cheer-0d41fbb569.mp3" as const;

/** Seconds. Used to size the celebration, not to schedule anything. */
export const CHEER_DURATION_SECONDS = 1.6;
